### ISSUE TITLE
httpclient 如何更新平台证书

### ISSUE THREAD

**Issue by wonderlq** [wechatpay-apiv3/wechatpay-apache-httpclient#1]
平台证书是会不定期更新。 但是httpclient  build 之后，httpclient 的平台证书固定下来了，那如何将平台证书更新？

**Comment by xy-peng** [comment]
> 平台证书是会不定期更新。 但是httpclient build 之后，httpclient 的平台证书固定下来了，那如何将平台证书更新？

你说得没错。目前只能通过外部工具更新证书，再重启服务来使用新证书。

从库的设计上来说，是计划有扩展的，可通过实现新的verifier来达到证书更新，比如内部定时更新证书，诸如此类。

从架构上来说，我觉得采用类似中心服务器，负责私钥证书管理更新、签名验签更合理。这时的signer/verifier走rpc去交给中心服务器干活，更安全，更职责单一。

总而言之，我们会提供内部定时更新证书的verifier实现。也欢迎开发者参与建设，提交pr。

**Comment by wonderlq** [comment]
ok ，了解了。另外希望能提供 回调通知消息的验签实现，目前只有对response 的签名验签。
