### ISSUE TITLE
[ERROR] - 商户证书为空 DefaultVerifier.verify(CertificatesManager.java:84) 

### ISSUE THREAD

**Issue by leon-W-yao** [wechatpay-apiv3/wechatpay-apache-httpclient#107]
static {
        try {
            log.info("init ==============================================");
            // 获取证书管理器实例
            CertificatesManager certificatesManager = CertificatesManager.getInstance();
            // 向证书管理器增加需要自动更新平台证书的商户信息
            certificatesManager.putMerchant(merchantId, new WechatPay2Credentials(merchantId,
                    new PrivateKeySigner(merchantSerialNumber, merchantPrivateKey)), apiV3Key.getBytes(StandardCharsets.UTF_8));
            // 从证书管理器中获取verifier
            verifier = certificatesManager.getVerifier(merchantId);
        } catch (Exception e) {
            log.error("init === Verifier  CertificatesManager fail", e);
            throw new RuntimeException("证书初始化失败");
        }
    }

报商户证书为空，
版本0.4.2   为啥呢？求大佬解答

**Comment by leon-W-yao** [comment]
String notifyBody = readData(request);
//            weChatPayNotify = JSONObject.parseObject(notifyBody, WeChatPayNotify.class);

            // 构建request，传入必要参数
            NotificationRequest notificationRequest = new NotificationRequest.Builder()
                    .withSerialNumber(merchantSerialNumber)
//                    .withNonce(weChatPayNotify.getResource().getNonce())
                    .withNonce(request.getHeader(WECHAT_PAY_NONCE))
                    .withTimestamp(request.getHeader(WECHAT_PAY_TIMESTAMP))
                    .withSignature(request.getHeader(WECHAT_PAY_SIGNATURE))
                    .withBody(notifyBody)
                    .build();
            NotificationHandler handler = new NotificationHandler(verifier, apiV3Key.getBytes(StandardCharsets.UTF_8));
            // 验签和解析请求体
            Notification notification = handler.parse(notificationRequest);

**Comment by lianup** [comment]
> String notifyBody = readData(request); // weChatPayNotify = JSONObject.parseObject(notifyBody, WeChatPayNotify.class);
> 
> ```
>         // 构建request，传入必要参数
>         NotificationRequest notificationRequest = new NotificationRequest.Builder()
>                 .withSerialNumber(merchantSerialNumber)
> ```
> 
> // .withNonce(weChatPayNotify.getResource().getNonce()) .withNonce(request.getHeader(WECHAT_PAY_NONCE)) .withTimestamp(request.getHeader(WECHAT_PAY_TIMESTAMP)) .withSignature(request.getHeader(WECHAT_PAY_SIGNATURE)) .withBody(notifyBody) .build(); NotificationHandler handler = new NotificationHandler(verifier, apiV3Key.getBytes(StandardCharsets.UTF_8)); // 验签和解析请求体 Notification notification = handler.parse(notificationRequest);

`merchantSerialNumber`确认下这里传入的是否为微信支付平台证书序列号呢？

**Comment by leon-W-yao** [comment]
> > String notifyBody = readData(request); // weChatPayNotify = JSONObject.parseObject(notifyBody, WeChatPayNotify.class);
> > ```
> >         // 构建request，传入必要参数
> >         NotificationRequest notificationRequest = new NotificationRequest.Builder()
> >                 .withSerialNumber(merchantSerialNumber)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > // .withNonce(weChatPayNotify.getResource().getNonce()) .withNonce(request.getHeader(WECHAT_PAY_NONCE)) .withTimestamp(request.getHeader(WECHAT_PAY_TIMESTAMP)) .withSignature(request.getHeader(WECHAT_PAY_SIGNATURE)) .withBody(notifyBody) .build(); NotificationHandler handler = new NotificationHandler(verifier, apiV3Key.getBytes(StandardCharsets.UTF_8)); // 验签和解析请求体 Notification notification = handler.parse(notificationRequest);
> 
> `merchantSerialNumber`确认下这里传入的是否为微信支付平台证书序列号呢？

嗯嗯  传错了， 已解决 谢谢

**Comment by lidaoyang** [comment]
> > String notifyBody = readData(request); // weChatPayNotify = JSONObject.parseObject(notifyBody, WeChatPayNotify.class);
> > ```
> >         // 构建request，传入必要参数
> >         NotificationRequest notificationRequest = new NotificationRequest.Builder()
> >                 .withSerialNumber(merchantSerialNumber)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > // .withNonce(weChatPayNotify.getResource().getNonce()) .withNonce(request.getHeader(WECHAT_PAY_NONCE)) .withTimestamp(request.getHeader(WECHAT_PAY_TIMESTAMP)) .withSignature(request.getHeader(WECHAT_PAY_SIGNATURE)) .withBody(notifyBody) .build(); NotificationHandler handler = new NotificationHandler(verifier, apiV3Key.getBytes(StandardCharsets.UTF_8)); // 验签和解析请求体 Notification notification = handler.parse(notificationRequest);
> 
> `merchantSerialNumber`确认下这里传入的是否为微信支付平台证书序列号呢？

<img width="899" alt="image" src="https://user-images.githubusercontent.com/26211950/161422397-e2e448ca-59a0-4f1c-a218-763652a9740e.png">
WechatPayHttpClientBuilder builder的时候里面的merchantSerialNumber是商户API证书的证书序列号和密钥。

在定时更新平台证书的功能里的mchSerialNo 和 merchantSerialNumber是一样的吗？还是mchSerialNo是商户API证书的xu序列号，merchantSerialNumber是平台证书的序列号呢？

<img width="976" alt="image" src="https://user-images.githubusercontent.com/26211950/161422468-b3cd09a4-4efd-42c9-9e45-3a69231f14c5.png">

**Comment by lidaoyang** [comment]
更新平台证书的功能可以更新商户API证书吗？
