### ISSUE TITLE
what's the stable version till now? // 2022-2-16

### ISSUE THREAD

**Issue by CrossLee** [wechatpay-apiv3/wechatpay-apache-httpclient#108]
0.4.2 is mentioned beta, so 0.4.1 is stable version?

**Comment by xy-peng** [comment]
发布遵循 [语义化版本](https://semver.org/lang/zh-CN/)。1.0 之前所有版本都标注成 beta，主要是接口“可能”会变化。

> 主版本号为零（0.y.z）的软件处于开发初始阶段，一切都可能随时被改变。这样的公共 API 不应该被视为稳定版。

当前版本经过了我们的测试，可以在测试验证后投入生产环境的。
