### ISSUE TITLE
Go语言版本的apiv3支持

### ISSUE THREAD

**Issue by aosfather** [wechatpay-apiv3/wechatpay-apache-httpclient#11]
已经实现了go语言版本的apiv3的实现，我看官方文档中的示例代码等都不全。
该项目已经能跑通，并验证了获取商户实名状态的查询。希望可以合作。
地址如下：
https://github.com/aosfather/bingo_wx/tree/master/apiv3

**Comment by xy-peng** [comment]
欢迎欢迎👏

非常感谢，也希望有更多的商户开发者能够参与进来一起完善。

不知道你的完整计划是怎么样的？方便的话，邮件给我联系方式吧。希望bingo_wx/apiv3能作为独立的项目，加上足够的文档、测试代码、示例。

**Comment by xy-peng** [comment]
https://github.com/wechatpay-apiv3/wechatpay-go
