### ISSUE TITLE
AutoUpdateCertificatesVerifier过期注释的类写错，应改为CertificatesManager

### ISSUE THREAD

**Issue by Aerozb** [wechatpay-apiv3/wechatpay-apache-httpclient#110]
![image](https://user-images.githubusercontent.com/37774577/154613792-878f8776-0038-4ed3-94d7-3778864c35ad.png)
ScheduledUpdateCertificatesVerifier没有这个类，应该是CertificatesManager

**Comment by xy-peng** [comment]
@Aerozb  发 PR ？

**Comment by lianup** [comment]
感谢指正，欢迎提PR修改。
