### ISSUE TITLE
你们写这么个贵东西不能出个完整版的demo吗，都sdk了还这么难用能不能去看看隔壁别人sdk什么样，3.0啊！

### ISSUE THREAD

**Issue by IDEA-Fang** [wechatpay-apiv3/wechatpay-apache-httpclient#112]

**Comment by IDEA-Fang** [comment]
![image](https://user-images.githubusercontent.com/38692833/154715193-2708865e-75ba-499f-a5c4-e9dcb57fc6aa.png)

**Comment by xy-peng** [comment]
我们这块的目标是，API和文档、SDK、Demo形成一个整体，降低开发者的学习成本，让大家把精力都放在业务系统的对接上。

以后会越做越好的。

**Comment by ye21st** [comment]
支持

**Comment by ye21st** [comment]
很多时候确实文档看不懂，还要去看源码。

**Comment by xy-peng** [comment]
duplicate, #91

**Comment by IDEA-Fang** [comment]
> 带业务接口的SDK已经在本年度规划，准备开发中。

背后中国多少开发者你们自己想想，睡觉不怕被几百万人戳你们脊梁骨嘛

**Comment by IDEA-Fang** [comment]
> 我们这块的目标是，API和文档、SDK、Demo形成一个整体，降低开发者的学习成本，让大家把精力都放在业务系统的对接上。
> 
> 以后会越做越好的。

ppt饼画完了麻烦落地，老板，几年了，老板，把团队成本转接到国内开发者身上马老板的意思？上线之前麻烦你们自己从0去写一波代码对接一遍系统，麻烦设置成kpi

**Comment by IDEA-Fang** [comment]
![image](https://user-images.githubusercontent.com/38692833/158007632-63b8478a-0245-49b1-9b22-3b920640e6b6.png)

**Comment by qxdn** [comment]
我也想说，看完之后还是不太明白
