### ISSUE TITLE
JSAPI 签名类建议

### ISSUE THREAD

**Issue by lixiuwen** [wechatpay-apiv3/wechatpay-apache-httpclient#113]
这个签名结果类`com.wechat.pay.contrib.apache.httpclient.auth.Signer.SignatureResult`中sign和certificateSerialNumber两个属性，能不能加个get 方法，jspapi签名要用到这个类，结果还得自己改源码

**Comment by lianup** [comment]
是指jsapi的哪个接口，能否说下具体使用场景？

**Comment by lixiuwen** [comment]
JSAPI调起支付API，需要进行参数签名得到paySign 这个参数，刚好需要使用到PrivateKeySigner#sign方法，该方法的返回值是SignatureResult，但是SignatureResult这个类里面的sign属性并没有get 方法
