### ISSUE TITLE
请求头Authorization问题，前端调起支付验签失败

### ISSUE THREAD

**Issue by mrjiangxb** [wechatpay-apiv3/wechatpay-apache-httpclient#114]
下单成功后，前端调起支付时，需要nonceStr、timeStamp，这两个参数需要跟下单时构造请求头Authorization时使用的nonceStr、timeStamp保持一致，但是这一步是被封闭在sdk中的，无法取到一致的参数，导致前端调起支付时验签失败。
![1](https://user-images.githubusercontent.com/51499602/155081904-e71fee5a-c686-440b-8863-3c84b73ff504.GIF)
![2](https://user-images.githubusercontent.com/51499602/155082157-7f6c4901-bc3a-4b29-b8f6-7a8967a7026b.GIF)

目前我是通过覆盖文件的方式在 WechatPay2Credentials 中加入nonceStr、timeStamp字段并且加入相应的构造函数，在new对象时主动传参。
`
public WechatPay2Credentials(String merchantId, Signer signer, String nonceStr, Long timestamp) {
        this.merchantId = merchantId;
        this.signer = signer;
        this.nonceStr = nonceStr;
        this.timestamp = timestamp;
    }
`
![3](https://user-images.githubusercontent.com/51499602/155083930-c5418815-021f-42a7-8d23-d310e1bb39df.GIF)
sdk有别的处理方式吗？我没找到

**Comment by xy-peng** [comment]
> 下单成功后，前端调起支付时，需要nonceStr、timeStamp，这两个参数需要跟下单时构造请求头Authorization时使用的nonceStr、timeStamp保持一致

据我所知，没有这个限制

**Comment by mrjiangxb** [comment]
刚试了下，确实没这个限制，是我别的地方有问题
