### ISSUE TITLE
什么时候有node版的

### ISSUE THREAD

**Issue by MJcc1111** [wechatpay-apiv3/wechatpay-apache-httpclient#116]
什么时候有node版的，麻溜点。

**Comment by xy-peng** [comment]
暂时请先参考下社区的微信开发者提供的各个语言的库，开发者社区有个[推荐列表](https://developers.weixin.qq.com/community/pay/doc/00022e47830e90adbd2c507c951801)。温馨提示，使用第三方库建议仔细测试并留意风险。

**Comment by Eric-Lee-Handyman** [comment]
如楼上所说，nodejs语言的可参考社区的版本。
目前正在规划新版本的Java SDK。

**Comment by MJcc1111** [comment]
大家很棒。nice。继续加油。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月28日(星期一) 凌晨0:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wechatpay-apiv3/wechatpay-apache-httpclient] 什么时候有node版的 (Issue #116)





 
如楼上所说，nodejs语言的可参考社区的版本。
 目前正在规划新版本的Java SDK。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
