### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Asuna1204** [wechatpay-apiv3/wechatpay-apache-httpclient#117]
notification = (Notification)objectReader.readValue(body, Notification.class)
![weixinpayscore](https://user-images.githubusercontent.com/44660583/155948062-766e1e85-7c66-424b-bfa1-983446a02caa.png)
;

**Comment by lianup** [comment]
业务代码中是否已有jackson库？SDK使用的jackson版本为2.12.5

**Comment by Asuna1204** [comment]
好的，谢谢

**Comment by Asuna1204** [comment]
感谢，已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月28日(星期一) 下午4:19
收件人: ***@***.***&gt;; 
抄送: "so ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wechatpay-apiv3/wechatpay-apache-httpclient] NoSuchMethodError (Issue #117)





 
业务代码中是否已有jackson库？SDK使用的jackson版本为2.12.5
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xy-peng** [comment]
@Asuna1204 hello，你使用的jackson版本是？

**Comment by Asuna1204** [comment]
2.8.10




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaoyu ***@***.***&gt;; 
发送时间: 2022年3月2日(星期三) 上午9:41
收件人: ***@***.***&gt;; 
抄送: "so ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wechatpay-apiv3/wechatpay-apache-httpclient] NoSuchMethodError (Issue #117)





 
@Asuna1204 hello，你使用的jackson版本是？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
