### ISSUE TITLE
APIv3调用jsapi创建订单接口，返回400 Bad Request Chunked: false

### ISSUE THREAD

**Issue by GongZhengMe** [wechatpay-apiv3/wechatpay-apache-httpclient#129]
完全使用官方提供的sdk工具封装，调用样例，然后调用jsapi的下单接口，httpResponse出现这个问题
`HttpResponseProxy{HTTP/1.1 400 Bad Request [Server: nginx, Date: Thu, 31 Mar 2022 08:40:49 GMT, Content-Type: application/json; charset=utf-8, Content-Length: 92, Connection: keep-alive, Keep-Alive: timeout=8, Cache-Control: no-cache, must-revalidate, X-Content-Type-Options: nosniff, Request-ID: 0891D295920610860318D7DB8C582093AF0128EA9805-270924337, Content-Language: zh-CN, Wechatpay-Nonce: 7e42d86607aaa1deb8f43f57ea116102, Wechatpay-Signature: slAGgr1yl1OO/qduUA9dvp1fvcB6aV/oY1FhULxUWRTaE6R2vggU8Hf2Kg1pwtgk1z9S0ilaFK6B4d2BI7dYgk82LjjVQj9V0GqOSu+lvoB/VXEwf1p7F5DHOipqHNRz3ESWVfJ2VfZ7lYIoZ2nW2QzGjLRqFFSOBmXXF8yg9akUhMWL1HLQl+6JdTnVc3cTUorGu6pTphEghrshRAV2k7ruHDitRaxzvXkLUFuyy8Mpzc50CpFPC/I7rZ+obQv5NEiWyMacDPKsMUgkMIsaXB+NhlJkaE8xnJf9R1K4YPvxH/fy0/8OxeOOqdkFJPPVEeXRignRqHKu3TFwDz+uhQ==, Wechatpay-Timestamp: 1648716049, Wechatpay-Serial: 4534ACDA663850A04AD37B52BD48E1D84D841E86, Wechatpay-Signature-Type: WECHATPAY2-SHA256-RSA2048] ResponseEntityProxy{[Content-Type: application/json; charset=utf-8,Content-Length: 92,Chunked: false]}}`

我的代码如下
```
 val wechatPayClientBuild =
                getWechatPayClientBuild(
                    wechatPayParam.merchantId!!,
                    wechatPayParam.merchantSerialNumber!!,
                    wechatPayParam.apiV3Key!!
                )
            val httpClient: CloseableHttpClient = wechatPayClientBuild.build()
            //设置微信必要请求头信息
            val httpPost: HttpPost = HttpPost(url);
            httpPost.addHeader("Accept", "application/json")
            httpPost.addHeader("Content-type","application/json; charset=utf-8");
            var bos :ByteArrayOutputStream  =  ByteArrayOutputStream()
            var objectMapper: ObjectMapper =  ObjectMapper()
            var rootNode: ObjectNode = objectMapper.createObjectNode();
            rootNode.put("mchid","1900009191")
                .put("appid", "wxd678efh567hg6787")
                .put("description", "Image形象店-深圳腾大-QQ公仔")
                .put("notify_url", "https://www.weixin.qq.com/wxpay/pay.php")
                .put("out_trade_no", "1217752501201407033233368018");
            rootNode.putObject("amount")
                .put("total", 1)
                .put("currency","CNY")
            rootNode.putObject("payer")
                .put("openid", "oUpF8uMuAJO_M2pxb1Q9zNjWeS6o");
            objectMapper.writeValue(bos, rootNode);
            httpPost.entity = StringEntity(bos.toString("UTF-8"), "UTF-8");
            //设置requestBody
//            httpPost.entity = StringEntity(bodyJsonStr,"UTF-8")
            var response = httpClient.execute(httpPost)
```
完全按照文档配置HTTPCLIENT并使用demo数据调试
该httpclient调用获取平台证书接口正常
调用下单接口出现如上问题，请问是什么原因导致这个问题

**Comment by lianup** [comment]
参考[接口规则](https://wechatpay-api.gitbook.io/wechatpay-api-v3/wei-xin-zhi-fu-api-v3-jie-kou-gui-fan#cuo-wu-xin-xi)，400是因为协议或者参数非法，可以看请求返回体中的具体错误信息。
看header中设置的`merchantId`与post请求体中的`mchid`不一致，把这个修改一下试试？

**Comment by GongZhengMe** [comment]
> 

请问下是不是要把所有证书和测试的用例都匹配，并且使用的openid要与appid真实对应才可以进行调试。我现在拿不到真实的open_id,其他参数都匹配，但是open_id用的demo中的，也是这个报错

**Comment by lianup** [comment]
是的。现在你调用的就是真实的现网环境，测试数据是调不通的。

**Comment by GongZhengMe** [comment]
> 是的。现在你调用的就是真实的现网环境，测试数据是调不通的。

好的，我到时候拿到真实的该公众号下的open_id再调试下， 如果没有问题我会关闭这个issue，谢谢回复~

**Comment by GongZhengMe** [comment]
今天用了openId测试了,很丝滑,sdk的demo全部过了,谢谢~很舒服
