### ISSUE TITLE
一直报错啊

### ISSUE THREAD

**Issue by lvgaga** [wechatpay-apiv3/wechatpay-apache-httpclient#130]
Cause: org/gradle/api/internal/plugins/DefaultConvention

**Comment by lianup** [comment]
IDE是否为IDEA？

**Comment by lvgaga** [comment]
> IDE是否为IDEA？

是

**Comment by lvgaga** [comment]
Cause: org/gradle/api/internal/plugins/DefaultConvention 
我的 idea是2018 3.3的 使用gradle6.4.1的不行么?

**Comment by lianup** [comment]
gradle 6.4.1 是2020年才发布的，你可以升级 IDEA 或者换个低版本的 Gradle 试试。

**Comment by lvgaga** [comment]
> gradle 6.4.1 是2020年才发布的，你可以升级 IDEA 或者换个低版本的 Gradle 试试。

换了idea的版本可以了

**Comment by lvgaga** [comment]
> gradle 6.4.1 是2020年才发布的，你可以升级 IDEA 或者换个低版本的 Gradle 试试。

CertificatesManagerTest 这个测试类怎么用啊 谢谢

**Comment by lianup** [comment]
把真实的privateKey、mchId、mchSerialNo、apiV3Key填进去就可以运行测试用例。
