### ISSUE TITLE
建议增加okhttp的适配器、http池化参数（如最大线程池）可以通过配置中心写入httpclient

### ISSUE THREAD

**Issue by dongyulongnet** [wechatpay-apiv3/wechatpay-apache-httpclient#131]
建议增加okhttp的适配器、http池化参数（如最大线程池）可以通过配置中心写入httpclient

**Comment by xy-peng** [comment]
1. okhttp的支持，我们计划放在新的SDK中了。也欢迎贡献代码。
2. `WechatPayHttpClientBuilder` 继承至 `HttpClientBuilder`，HTTP 连接相关参数可以使用 `HttpClientBuilder. setConnectionManager()` 等方法设置

**Comment by jcjgithub** [comment]
我最近这段时间封装了微信的sdk 希望能帮上大家的忙
<dependency>
  <groupId>io.gitee.aj_mayu</groupId>
  <artifactId>wx-pay-sdk</artifactId>
  <version>1.0.0</version>
</dependency> 已经放入到maven中央仓库 感兴趣的可以去下载

**Comment by xy-peng** [comment]
> io.gitee.aj_mayu
wx-pay-sdk
1.0.0
已经放入到maven中央仓库 感兴趣的可以去下载

感谢贡献社区SDK，不过没看到源代码？

处于安全考虑，我还是提醒大家谨慎选择。

**Comment by jcjgithub** [comment]
放在码云上面
https://gitee.com/aj_mayu/wx-pay-sdk

**Comment by dongyulongnet** [comment]
> 放在码云上面 https://gitee.com/aj_mayu/wx-pay-sdk

我们现在都从V2迁到V3了，你这个是V2的，个人不太喜欢forest这个插件，太花里胡哨了，原生的openFeign就蛮不错（虽然也有一些不太好的地方，比如@QueryMap注解,单整体风格都很简洁）

**Comment by jcjgithub** [comment]
多谢反馈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月21日(周四) 中午12:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wechatpay-apiv3/wechatpay-apache-httpclient] 建议增加okhttp的适配器、http池化参数（如最大线程池）可以通过配置中心写入httpclient (Issue #131)




  
放在码云上面 https://gitee.com/aj_mayu/wx-pay-sdk
  
***@***.***注解,单整体风格都很简洁）
