### ISSUE TITLE
jsSDK支付的签名算法能否提供一个RSA的签名示例？

### ISSUE THREAD

**Issue by dawang1024** [wechatpay-apiv3/wechatpay-apache-httpclient#135]
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html
![image](https://user-images.githubusercontent.com/67535305/165492704-19bb0132-bccc-4989-b208-67d9e2f5f55e.png)

这个地方写的太粗糙了，对接难度+N

**Comment by lianup** [comment]
可以在[微信JS-SDK反馈](https://developers.weixin.qq.com/community/minihome/question/1277775808983138305)反馈一下。

**Comment by xy-peng** [comment]
@dawang1024 如果要解决问题，可以先看微信支付侧的 [JSAPI调起支付](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_4.shtml)。

**Comment by dawang1024** [comment]
> 

好的，看到了
