### ISSUE TITLE
回调验签失败

### ISSUE THREAD

**Issue by advertflow** [wechatpay-apiv3/wechatpay-apache-httpclient#138]
![image](https://user-images.githubusercontent.com/22832157/167805664-c8d1ebd6-0a34-4e3d-b4ea-cc92a200d4d3.png)
![image](https://user-images.githubusercontent.com/22832157/167805831-253b0467-7b5e-4c12-af4d-571b71cd3aa6.png)

**Comment by advertflow** [comment]
![image](https://user-images.githubusercontent.com/22832157/167805932-f8f53b74-b0cd-4413-ac28-ef193d88d41c.png)
body的格式跟文档一致

**Comment by lianup** [comment]
可以先对比一下传入`NotificationHandler`的信息`serialNumber`、`timestamp`、`nonce`、`body`是否跟原始的HTTP请求参数完全一致，不一致会导致验签失败。

**Comment by advertflow** [comment]
通gu过线上打印直接复制的，本地断点测试也是对上的
![微信截图_20220511165759](https://user-images.githubusercontent.com/22832157/167812286-79ef0ecb-a517-47b7-aace-56e82b57c373.png)

**Comment by advertflow** [comment]
不会，我通过线上回调执行逻辑，也会出错的

**Comment by lianup** [comment]
我验证了id为`d4785163-ff81-5ed4-b828-e124183b37b3`的签名，是可以通过的。感觉是参数的问题。body返回有中文，看下是否有编码不对导致数据不正确的问题呢？
另外，可以贴下`body`等参数的获取代码，我来一起看看。

**Comment by advertflow** [comment]
String body = "{\"id\":\"d4785163-ff81-5ed4-b828-e124183b37b3\",\"create_time\":\"2022-05-11T14:56:22+08:00\",\"resource_type\":\"encrypt-resource\",\"event_type\":\"TRANSACTION.SUCCESS\",\"summary\":\"支付成功\",\"resource\":{\"original_type\":\"transaction\",\"algorithm\":\"AEAD_AES_256_GCM\",\"ciphertext\":\"tGT24ucHE90+h5NwRrNjqahN8YWeTudUCAEHwqhSBm+bg+9bSt5FlNC+m7jIlSzo8oOUaIRAbxcBnVFPhG4Xz2g7X2ys2ShvRwVdPpnU65IU5pB4PSFQy5K4w1xWf2zwnRBYtQIh2O/tjrabGjp/NlcfmSEdDmkszPsPu5rIx4K9NNYReBX0hk5dPBDfD5zzRHl9+RwZ4wpvifriqOIIvFxs3G5DtPEHSoZC8JqKFc1KatrR267qy5XTNWZWD9xT2ssUoEW4Dw96zhQVnhK+oSlhJdzjUbTGqVLED5FP/TrcP+0WM8re2o7NdCMjqveUbUgOLrgj8u4YMBBsPER3ae0317wTp+9Cvf+M4N+HhFCkS/uE9NMRjvHkJQYGFCztg5Hlh3CkU6qsnUqtVU34qT9nGaaBxZBkbMgd5sedfYlPP2Vml4xHrkxrX1dCTDLVwQ7vDQ/DrNuPkGd+W+2a6QAlCuPEEaHY7vfDXrZ71RcjJSkuxoOgGpPlP4nVGKh6bmBO6M6ZZehBaw5ragItocEkpnFnQ/wqBsriJ9DJpEc2gJufjlDbxziJGtmZ42PmL51Z2rQlpT+ped/xFby+QWTp8VRyLJYGYkAJ9lbnJedM3Y+B+u+EULN/HJJ0rUkfEiAz7zc0RwyD01IwoOz5OwLV4siEsyVpk8B0WiPWmzYxzXc0kXHv+70\\u003d\",\"associated_data\":\"transaction\",\"nonce\":\"PxI2G23L2Xp3\"}}";

**Comment by advertflow** [comment]
编码需要如何处理下吗

**Comment by advertflow** [comment]
使用定时更新平台证书功能，应该不用管平台证书到期时间了吧

**Comment by advertflow** [comment]
谢谢，可以验签了

**Comment by lianup** [comment]
不客气，还有其他问题可以继续反馈，没有问题的话后续可以关闭issue。
