### ISSUE TITLE
0.4.6 签名出错是参数和证书有问题吗

### ISSUE THREAD

**Issue by NicolasOne** [wechatpay-apiv3/wechatpay-apache-httpclient#139]
应答的状态码不为200-299。status code[401]

List<X509Certificate> certs = new ArrayList<>();
		certs.add(PemUtil.loadCertificate(new ByteArrayInputStream(certificate.getBytes("utf-8"))));
		WechatPayHttpClientBuilder builder = WechatPayHttpClientBuilder.create()
				.withMerchant(merchantId, merchantSerialNumber, merchantPrivateKey)
				.withWechatPay(certs);

**Comment by lianup** [comment]
看一下日志打印出来的Authorization头的信息是否符合[构造签名串](https://wechatpay-api.gitbook.io/wechatpay-api-v3/qian-ming-zhi-nan-1/qian-ming-sheng-cheng)规则，另外可以提供下请求的`Request-ID`。

**Comment by NicolasOne** [comment]
08CFCBF1930610C20518C6B5C05520DC9A012898E905-269546525



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月12日 10:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wechatpay-apiv3/wechatpay-apache-httpclient] 0.4.6 签名出错是参数和证书有问题吗 (Issue #139) |

看一下日志打印出来的Authorization头的信息是否符合构造签名串规则，另外可以提供下请求的Request-ID。

**Comment by NicolasOne** [comment]
request headers[[Accept: application/json, 
Authorization: WECHATPAY2-SHA256-RSA2048 
mchid="xxxxxxxxx",
nonce_str="vcvxiJC3mkC9mvOFn8FTfd2lXoMlIgbW",
timestamp="1652319696",
serial_no="xxxxxxx",
signature="xxxxxxxxxxMpZd2Hj9rb3NAxuHZeb+wgYiw9woqyfYMUAxMXqWn0WMNxjPeu3lZ8i7SIUDBh3okRAKI9zjKP+A2UQNDwZzu0d+flZGR6MhbAI50a11K
cIg5S1aLNPVcs7bmAAA71cbAsGPC/SX/teskHyH1wryUO+8DHtzKUBpKZiw4gtQz9uyj4MKoLbvEjyJItV1AwLHU6wPkqltkMTt2WQ4G9GGnK/97Fhu6SMvm5HjHWxbPx
BE3Jega5Y6Jo1l3/Quvb/eKQrtAATgt23LuPk5zNZr4hEAXbBtafxtOuaeA82kydlLYlnaMrXpm6RWe9fOvWgvJsxyh/1cg==", 
Content-Length: 143, 
Content-Type: application/json; 
charset=UTF-8,
Host: api.mch.weixin.qq.com, 
Connection: Keep-Alive, 
User-Agent: WechatPay-Apache-HttpClient/0.4.6 (Windows 10/10.0) Java/1.8.0_102, 
Accept-Encoding: gzip,deflate
]]

**Comment by NicolasOne** [comment]
> 看一下日志打印出来的Authorization头的信息是否符合[构造签名串](https://wechatpay-api.gitbook.io/wechatpay-api-v3/qian-ming-zhi-nan-1/qian-ming-sheng-cheng)规则，另外可以提供下请求的`Request-ID`。

返回信息里的序列号和我用的不一样,"name":"Wechatpay-Serial","value":"5B08AE30BF7D8E8ABA42499F5F3D8Exxxxxx","valuePos":17}

**Comment by NicolasOne** [comment]
自己找到了问题，还是参数那里，退款的时候二选一，只传一个就行
