### ISSUE TITLE
 普通服务商-特约商户进件-提交申请单-敏感信息加密

### ISSUE THREAD

**Issue by saturdaysunny** [wechatpay-apiv3/wechatpay-apache-httpclient#14]
”开发者应当使用微信支付平台证书中的公钥，对上送的敏感信息进行加密。“
我采用AutoUpdateCertificatesVerifier自动更新证书，我需要拿到证书才能进行加密，但是AutoUpdateCertificatesVerifier中的verifier字段是private的，CertificatesVerifier中的private final HashMap<BigInteger, X509Certificate> certificates 也是私有的。目前我是采用反射的方式获取平台证书的。

**Comment by xy-peng** [comment]
是希望有方法可以取到证书？

**Comment by saturdaysunny** [comment]
是的，希望AutoUpdateCertificatesVerifier提供方法获取证书，用于加密敏感信息

**Comment by Sneakydogs** [comment]
同求啊，痛点。。。。

**Comment by saturdaysunny** [comment]
"某些情况下，微信支付会更新平台证书。这时，商户有多个微信支付平台证书可以用于加密。为了保证解密顺利，商户发起请求的HTTP头部中应包括证书序列号，以声明加密所用的密钥对和证书。
商户上送敏感信息时使用微信支付平台公钥加密，证书序列号包含在请求HTTP头部的Wechatpay-Serial"。
目前verifier.getValidCertificate();只返回了证书，没有返回证书序列号，敏感信息加密的数据提交的时候需要带上请求头**Wechatpay-Serial**，作者应该把证书序列号也一起返回出来

**Comment by xy-peng** [comment]
证书直接用[getSerialNumber](https://docs.oracle.com/javase/8/docs/api/javax/security/cert/X509Certificate.html#getSerialNumber--)方法就可以拿到证书序列号，不过是BigInterger，还要再转一下

**Comment by xiongdashan** [comment]
> 证书直接用[getSerialNumber](https://docs.oracle.com/javase/8/docs/api/javax/security/cert/X509Certificate.html#getSerialNumber--)方法就可以拿到证书序列号，不过是BigInterger，还要再转一下

感谢，看了一下是需要对Receivers中的Name加密， 但我使用下面的方式密的时候提示证书格式问题，是我使用的证书有问题吗？
代码：
```go
rs, err := wechat.GetPlatformCerts(mc_id, wxpayV3, certserialno, getPkContent())
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, val := range rs.Certs {
		fmt.Println(val.SerialNo)
		//fmt.Println(val.PublicKey)
	}

	cert := rs.Certs[0]

	client, err := wechat.NewClientV3(mc_id, certserialno, wxpayV3, getPkContent())
	client.SetPlatformCert([]byte(cert.PublicKey), cert.SerialNo).AutoVerifySign()

	if err != nil {
		fmt.Println(err)
		return
	}

	name, err := client.V3EncryptText("张三")

	if err != nil {
		fmt.Println(err)
		return
	}
```

Err信息：

```
x509.ParsePKCS1PublicKey：asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:708 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @4
```
