### ISSUE TITLE
回调验签报错，商户证书为空？？？

### ISSUE THREAD

**Issue by ljl215186** [wechatpay-apiv3/wechatpay-apache-httpclient#140]
一个商户，同一个证书序列号，证书存储时序列号竟然与拉取时序列号不同，只有一个生效证书
![image](https://user-images.githubusercontent.com/11437321/167978635-5563330c-8692-484f-b0e5-8a7662742564.png)
![image](https://user-images.githubusercontent.com/11437321/167979063-c9034dbe-736f-4182-bc82-0c79437ffa11.png)

验签时获取证书序列号变成了   158833791119106484143093832349489180329207073246

**Comment by lianup** [comment]
可以确认下构建`NotificationRequest`时传入`withSerialNumber`的是否为微信支付回调通知中带的平台证书序列号。

**Comment by yuefuqiangJohnny** [comment]
这个问题解决了吗？

**Comment by yuefuqiangJohnny** [comment]
请问这个问题解决了吗？

**Comment by Eric-Lee-Handyman** [comment]
这里应该是你使用的证书序列号不对导致的，请区分 商户API证书 跟 平台证书，具体可以参考：https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/zheng-shu#ping-tai-zheng-shu
