### ISSUE TITLE
这些垃圾代码的变量命名能不能统一下，净他妈误导人

### ISSUE THREAD

**Issue by ljl215186** [wechatpay-apiv3/wechatpay-apache-httpclient#141]
![image](https://user-images.githubusercontent.com/11437321/167983503-7556035b-b0bf-4863-9bd1-9c9cbf123d88.png)

**Comment by Eric-Lee-Handyman** [comment]
收到，确实是我们的问题。
命名不一致是有历史问题导致的，我们立即改。

**Comment by Eric-Lee-Handyman** [comment]
已修复，感谢反馈。
