### ISSUE TITLE
微信支付 Spring Boot Starter 项目请求友链？

### ISSUE THREAD

**Issue by JerryChin** [wechatpay-apiv3/wechatpay-apache-httpclient#144]
本 SDK 在 Spring Boot 环境下使用时需要编写不少代码，因此开发了 [微信支付 Spring Boot Starter 项目
](https://github.com/JerryChin/wechatpay-spring-boot-project) ，用户只需要指定配置参数即可完成 SDK 自动化配置，使用方式非常简单并提供文档和 Demo。

**Comment by xy-peng** [comment]
社区贡献的库，欢迎发到[开发者社区](https://developers.weixin.qq.com/community/pay/doc/00022e47830e90adbd2c507c951801)
