### ISSUE TITLE
16:23:19.541 [http-nio-8080-exec-3] ERROR c.w.p.c.a.h.c.CertificatesManager - [verify,84] - 商户证书为空，serialNumber:43C8FB6FD8EF3880EDFFBA0E54B484A391ADE99E

### ISSUE THREAD

**Issue by wwt164888** [wechatpay-apiv3/wechatpay-apache-httpclient#145]
![image](https://user-images.githubusercontent.com/62713172/170218968-2fbd11bc-bf00-409e-bdbc-1b2b57d79426.png)

java.lang.RuntimeException: com.wechat.pay.contrib.apache.httpclient.exception.ValidationException: 验签失败：serial=[43C8FB6FD8EF3880EDFFBA0E54B484A391ADE99E] message=[1653467001
RCQnHXktqNtl6tRLuNSwsKwzT1gkkmiy

**Comment by xy-peng** [comment]
你好，你是如何初始化 notification 的？请检查下 verifier 的初始化是否成功，并参考 [回调通知的验签与解密](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%9B%9E%E8%B0%83%E9%80%9A%E7%9F%A5%E7%9A%84%E9%AA%8C%E7%AD%BE%E4%B8%8E%E8%A7%A3%E5%AF%86) 看看你初始化的部分。

verifier对应的商户号是收到回调的商户号吗？

**Comment by wwt164888** [comment]
解决了，使用的是自己的商户号
