### ISSUE TITLE
难用到令人无法呼吸,令人窒息的SDK

### ISSUE THREAD

**Issue by ezio7584** [wechatpay-apiv3/wechatpay-apache-httpclient#153]
..........挺佩服南三必胜客的.......这算摆烂的最高境界么

**Comment by Eric-Lee-Handyman** [comment]
这个只是一个apache的client，我们目前正在开发新版本的SDK，近期会发布出来。
如果有具体的建议 or 意见，可以提出来，感谢您的关注。

**Comment by ezio7584** [comment]
吐槽完了关闭
