### ISSUE TITLE
证书能通过私钥直接下载了，证书还有存在的必要吗？

### ISSUE THREAD

**Issue by zero47** [wechatpay-apiv3/wechatpay-apache-httpclient#154]
证书本来就是补充私钥泄露的安全问题，现在直接可以通过私钥下载，证书还有存在的必要吗？

**Comment by zero47** [comment]
> 不仅如此，**平台证书**还用于请求中[敏感字段的加密](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_3.shtml)。
> 
> 因此不论从何角度，平台证书的存在都是相当必要的。

我知道业务上的概念，但这么一弄，其实安全性和用私钥加密字段无什么区别了，安全性大打折扣。原本应该私钥负责普通安全级别没有很高的业务，证书负责交易上的业务。现在感觉都被拉成同一级别了。

**Comment by EmmetZC** [comment]
首先，隐私敏感字段是不应该用**私钥**加密的，因为普遍来讲证书是公开的（或者从安全等级上是**可以公开**的）。
如果用私钥来加密，证书解密的话，那就相当于用了一个人人可开的锁，这样的加密就达不到保密的目的了。

**Comment by zero47** [comment]
> 首先，隐私敏感字段是不应该用**私钥**加密的，因为普遍来讲证书是公开的（或者从安全等级上是**可以公开**的）。 如果用私钥来加密，证书解密的话，那就相当于用了一个人人可开的锁，这样的加密就达不到保密的目的了。

用私钥加密，公钥解密，私钥公钥都只存在**应用服务器**和**微信支付服务器**，这怎么会人人可开呢？
还有我觉得我们离题了。

**Comment by EmmetZC** [comment]
其次，
如我前面所讲，**商户私钥**才是用来认证商户身份的，**平台证书**并没有这个能力。这二者的功能并不重叠，并没有A替代B的说法。
所以你说的二者分别用在不同安全级别的业务上面，这个想法是不成立的。

**Comment by zero47** [comment]
@EmmetZC 兄弟没必要这么绕，我当然支持使用证书，我只是疑问**商户私钥**如果可以下载**平台证书**了，那这安全性将大大降低。

**Comment by EmmetZC** [comment]
> @EmmetZC 兄弟没必要这么绕，我当然支持使用证书，我只是疑问**商户私钥**如果可以下载**平台证书**了，那这安全性将大大降低。

我们来回顾一下上面的讨论：

你提出了以下观点：
1. 证书本来就是补充私钥泄露的安全问题
2. 原本应该私钥负责普通安全级别没有很高的业务，证书负责交易上的业务

以此给出最终的结论（或疑问）：**商户私钥如果可以下载平台证书了，那这安全性将大大降低**。

针对1，我在[第一次回复](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/issues/154#issuecomment-1162792013)中进行了解释和反驳。
针对2，我在[第四次回复](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/issues/154#issuecomment-1162818404)中进行了说明，你这个想法也是不成立的。

所以我也不明白，你得出此结论的原因是什么？能不能给出一些例子？

**Comment by zero47** [comment]
我也以我的角度来回顾一下上面的讨论：

我提出了如果证书可以保证独立，那么泄露了私钥在交易上依旧可控，现在允许下载后失去了这份天然的保障
你回复了业务上证书不负责保障私钥泄露问题。

我再提出了如果允许私钥下载证书，那这个安全性就基本等同于用私钥加密。（这里我没有声明说的是私钥泄露场景，我认为我们一直在此基础上讨论的）
你回复了私钥不能用来加密，证书才可以，不然人人都可以开锁。

我再补充公钥私钥都是两端保管，不会人人都能开锁。
你又说明了业务上私钥是身份，证书是加密手段。

我由此至终强调的都是你们允许私钥下载证书会带来私钥泄露后的最后一道天然屏障

**Comment by xy-peng** [comment]
微信支付 APIv3 使用了 [非对称式密码学](https://zh.wikipedia.org/wiki/%E5%85%AC%E5%BC%80%E5%AF%86%E9%92%A5%E5%8A%A0%E5%AF%86) 代替 v2 使用 APIkey 的对称加密。

> 公开密钥密码学（英语：Public-key cryptography）也称非对称式密码学（英语：Asymmetric cryptography）是[密码学](https://zh.wikipedia.org/wiki/%E5%AF%86%E7%A2%BC%E5%AD%B8)的一种[算法](https://zh.wikipedia.org/wiki/%E6%BC%94%E7%AE%97%E6%B3%95)，它需要两个[密钥](https://zh.wikipedia.org/wiki/%E5%AF%86%E9%92%A5)，一个是公开密钥，另一个是私有密钥；公钥用作加密，私钥则用作解密。

> 公钥可以公开，可任意向外发布；私钥不可以公开，必须由用户自行严格秘密保管，绝不透过任何途径向任何人提供，也不会透露给被信任的要通信的另一方。

> 公钥可以透过[数字证书认证机构](https://zh.wikipedia.org/wiki/%E6%95%B0%E5%AD%97%E8%AF%81%E4%B9%A6%E8%AE%A4%E8%AF%81%E6%9C%BA%E6%9E%84)签授的[电子证书](https://zh.wikipedia.org/wiki/%E9%9B%BB%E5%AD%90%E8%AD%89%E6%9B%B8)形式公布，接收者透过[信任链](https://zh.wikipedia.org/wiki/%E4%BF%A1%E4%BB%BB%E9%8F%88)形成一套完整的[公开密钥基础建设](https://zh.wikipedia.org/wiki/%E5%85%AC%E9%96%8B%E9%87%91%E9%91%B0%E5%9F%BA%E7%A4%8E%E5%BB%BA%E8%A8%AD)。

根据密码学，我们建议商户妥善保管私钥，而商户证书是可以公开的。

@zero47 是否把微信支付 APIv3 用到的证书跟 HTTPS 用到的包含了私钥的  SSL/TLS 证书混淆了？

以下是我们给商户准备中的密码学材料中的一页内容，可能看起来更直观一点。

<img width="1833" alt="image" src="https://user-images.githubusercontent.com/1812516/175010667-849352c3-c005-4210-949a-99b1282afa62.png">
