### ISSUE TITLE
平台证书序列号(Wechatpay-Serial)要怎么获取？

### ISSUE THREAD

**Issue by cuznjaclove** [wechatpay-apiv3/wechatpay-apache-httpclient#155]
新版添加了下载和更新平台证书的功能，但是在加密信息传递需要在请求头传入Wechatpay-Signature，我要从哪里获取？我尝试了verifier.getValidCertificate().getSerialNumber()，但似乎和获取平台证书返回body的serial_no不一致。

**Comment by cuznjaclove** [comment]
> 下载和更新，但是，但是，在加密的地方需要在请求版本中添加新的证书功能，但我们需要获取新的聊天功能，但我要获取证书（签名）。返回证书的serial_nobody。

` public String get(String requestUrl) {
        CloseableHttpClient httpClient;
        CloseableHttpResponse response;
        org.apache.http.HttpEntity entity;
        try {
            httpClient = getClient();
            HttpGet httpGet = new HttpGet(requestUrl);
            httpGet.addHeader("Accept", "application/json");
            httpGet.addHeader("User-Agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)");
            httpGet.addHeader("Wechatpay-Serial", String.valueOf(getSerialNumber()));
            response = httpClient.execute(httpGet);
            entity = response.getEntity();
            return EntityUtils.toString(entity);
        } catch (Exception e) {
            log.error("request wechat v3 api error,requestUrl:" + requestUrl, e);
        }
        return null;
    }

private BigInteger getSerialNumber() {
        return pubCert().getSerialNumber();
    }

    @SneakyThrows
    private X509Certificate pubCert() {
        Verifier verifier = getVerifier();
        return verifier.getValidCertificate();
    }

    @SneakyThrows
    private Verifier getVerifier() {
        PrivateKey merchantPrivateKey = PemUtil.loadPrivateKey(privateKey);
        CertificatesManager manager = CertificatesManager.getInstance();
        PrivateKeySigner signer = new PrivateKeySigner(mchSerialNumber, merchantPrivateKey);
        manager.putMerchant(mchId, new WechatPay2Credentials(mchId, signer), apiV3Key.getBytes(StandardCharsets.UTF_8));
        return manager.getVerifier(mchId);
    }
`

**Comment by cuznjaclove** [comment]
`public String get(String requestUrl) {
        CloseableHttpClient httpClient;
        CloseableHttpResponse response;
        org.apache.http.HttpEntity entity;
        try {
            httpClient = getClient();
            HttpGet httpGet = new HttpGet(requestUrl);
            httpGet.addHeader("Accept", "application/json");
            httpGet.addHeader("User-Agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)");
            httpGet.addHeader("Wechatpay-Serial", String.valueOf(getSerialNumber()));
            response = httpClient.execute(httpGet);
            entity = response.getEntity();
            return EntityUtils.toString(entity);
        } catch (Exception e) {
            log.error("request wechat v3 api error,requestUrl:" + requestUrl, e);
        }
        return null;
    }

private BigInteger getSerialNumber() {
        return pubCert().getSerialNumber();
    }

    @SneakyThrows
    private X509Certificate pubCert() {
        Verifier verifier = getVerifier();
        return verifier.getValidCertificate();
    }

    @SneakyThrows
    private Verifier getVerifier() {
        PrivateKey merchantPrivateKey = PemUtil.loadPrivateKey(privateKey);
        CertificatesManager manager = CertificatesManager.getInstance();
        PrivateKeySigner signer = new PrivateKeySigner(mchSerialNumber, merchantPrivateKey);
        manager.putMerchant(mchId, new WechatPay2Credentials(mchId, signer), apiV3Key.getBytes(StandardCharsets.UTF_8));
        return manager.getVerifier(mchId);
    }`

**Comment by xy-peng** [comment]
> 似乎和获取平台证书返回body的serial_no不一致

应该是一样的，下载器也是通过获取微信支付平台证书API下载证书的。

**Comment by cuznjaclove** [comment]
> > 似乎和获取平台证书的不同返回body的serial_no
> 
> 应该是一样的，下载器也是通过获取微信支付平台证书API下载证书的。

我针对com.wechat.pay.contrib.apache.httpclient.cert.CertificatesManager#downloadAndUpdateCert line:266本地调试看了一下，请求获取证书返回serial_no的是54D5XXXXXXXXXXXXXXXXXXE72【见下方第一个图】，但是line:267经过反序列化并解密（CertSerializeUtil.deserializeToCerts）后，返回的证书getSerialNumber()是
48XXXXXXXXXXXXXXX078【见下方第二个图】。怀疑是不是CertSerializeUtil.deserializeToCerts有问题

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/44158309/176074980-d7fe6a41-c5cd-4caa-8001-bf2df66b3c36.png">


![image](https://user-images.githubusercontent.com/44158309/176073756-edcae46f-6f51-45f1-bf4d-c6f8aa9700b9.png)

**Comment by cuznjaclove** [comment]
还有给个建议，最好把获取平台证书序列号(Wechatpay-Serial)的方式也写在readme里面。

**Comment by xy-peng** [comment]
我知道了。使用`X509.getSerialNumber()` 返回的是 BigInteger，需经过 `.toString(16)` 得到16进制输出才能得到证书序列号。

**Comment by cuznjaclove** [comment]
感谢回答，已解决
