### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by hson08** [wechatpay-apiv3/wechatpay-apache-httpclient#156]
![image](https://user-images.githubusercontent.com/40419401/177487754-171c5ae1-be8b-43cc-95de-1a29d0fb4af2.png)
不知道什么原因，执行到CloseableHttpResponse response = httpClient.execute(httpGet)这里就报这个。

**Comment by lianup** [comment]
你好，从报错信息中看，似乎是由 `Apache HttpClient` 引起的。SDK 使用的 `Apache HttpClient` 版本号为 4.5.13，请问你使用的版本号是？

**Comment by hson08** [comment]
![image](https://user-images.githubusercontent.com/40419401/177504287-089b0a31-051b-4693-a434-0e6cb2451e1f.png)
这个？
