### ISSUE TITLE
下载订单验签失败

### ISSUE THREAD

**Issue by M1SAK1TN** [wechatpay-apiv3/wechatpay-apache-httpclient#161]
调用API获取到下载订单的url
在调用下载订单API时提示验签失败，这是什么原因

**Comment by M1SAK1TN** [comment]
看到文档说要跳过验签流程，瞅瞅怎么弄

**Comment by lianup** [comment]
下载账单接口需要跳过验证签名流程，请参考 [如何下载平台证书？](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E5%B9%B3%E5%8F%B0%E8%AF%81%E4%B9%A6) 中设置空的应答签名器步骤。
其他业务请求请使用标准的初始化流程，务必验证应答签名。
