### ISSUE TITLE
是否支持内网环境通过代理服务器的方式使用CertificatesManager下载平台证书？

### ISSUE THREAD

**Issue by taojunyu** [wechatpay-apiv3/wechatpay-apache-httpclient#165]
如题，因为公司内网隔离，所以需要走代理方式访问微信api。请问是否支持内网环境通过代理服务器的方式使用CertificatesManager下载平台证书？

**Comment by xy-peng** [comment]
`CertificatesManager.setProxy()` 提供了设置代理的能力。 @taojunyu 看能否满足你的场景。

**Comment by taojunyu** [comment]
好的，我在最新的0.4.8里找到了该方法，但根据文档标注该版本暂为测试版本，请问一下是否能在使用稳定版本的基础上实现代理，比如自定义一个类继承CertificatesManager并重写其中的请求微信api方法，这样是否可行？或者是否有其他方式？

**Comment by xy-peng** [comment]
`0.4.8` 是线上生产环境可用的。测试版本只是一直沿用下来而已。

目前的实现方案的实现是有什么问题吗？

**Comment by taojunyu** [comment]
嗯嗯，只要0.4.8是生产可用就行，我这边主要是担心不是稳定版本会造成生产问题，多谢！
