### ISSUE TITLE
sdk如何调起sign的方法

### ISSUE THREAD

**Issue by angelology100** [wechatpay-apiv3/wechatpay-apache-httpclient#170]
https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter9_3_1.shtml
小程序和h5 的发卷都是单独只需要sign的，和前面的接口方式又不尽相同。sdk有可以直接获取sign的方法吗

**Comment by xy-peng** [comment]
目前可以直接构造一个 `PrivateKeySigner ` 来算签名。

我补充下常见问题。

**Comment by angelology100** [comment]
> 

我这里搞错了，https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter9_2_1.shtml 创建商家卷是v3的申请，所以误导自己发卷也是用到v3的sign去发卷，所以才提问了如何获取。PrivateKeySigner是可以获取到sign，但是现在用途并没单独用处。现在发卷是要用v2的签名的加密方式，和v3的签名方式不同。

**Comment by xy-peng** [comment]
商家券发券的定制业务逻辑，包含业务接口的 [wechatpay-java](https://github.com/wechatpay-apiv3/wechatpay-java) 可以提供解决方案。[wechatpay-apache-httpclient](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient) 没有计划支持 v2 签名。
