### ISSUE TITLE
对小程序支付生成的httpClient进行代理设置不生效

### ISSUE THREAD

**Issue by SJun12138** [wechatpay-apiv3/wechatpay-apache-httpclient#171]
build.setDefaultRequestConfig()、buile.setRoutePlanner()都不会生效

**Comment by xy-peng** [comment]
> build.setDefaultRequestConfig()、buile.setRoutePlanner()都不会生效

能否贴一下你的代码？你在其他支付方式设置代理是生效的？

**Comment by SJun12138** [comment]
因为考虑到与三方服务器的header中的校验，支付的采用的都是文档所提供SDK中的客户端API进行设置代理。在本次使用WechatPayHttpClientBuilder构建client时，使用原生HttpClientBuilder中的setDefaultRequestConfig()设置代理IP与端口，实际服务器中并不生效。

**Comment by SJun12138** [comment]
![image](https://user-images.githubusercontent.com/63095360/192208158-36decebe-5d3a-402d-a3a7-c7834589d270.png)

**Comment by SJun12138** [comment]
这是我在微信预支付请求中的方式，也是我遇见的问题代码块。感谢！![image](https://user-images.githubusercontent.com/63095360/192208400-1e1eb01f-d0f2-437f-8020-7b1b904b5e3e.png)

**Comment by xy-peng** [comment]
你试试 `WechatPayHttpClientBuilder::withProxy()` 设置代理是否有效呢？

**Comment by SJun12138** [comment]
> 你试试 `WechatPayHttpClientBuilder::withProxy()` 设置代理是否有效呢？

请问您说的是什么版本？我使用的wechatpay-apache-httpclient 0.4.2并没有您说的withPorxy()函数

**Comment by xy-peng** [comment]
#163 可以看下当时的讨论。

你可以升级到 `0.4.8` 版本，实现在 https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/bbe835bda309d367d66e2dce6154aa0b8b1eb55d/src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayHttpClientBuilder.java#L56

**Comment by SJun12138** [comment]
谢谢您，问题找到了，是因为我加载平台证书的时候采用的类AutoUpdateCertificatesVerifier不能设置代理，所以一直卡在这一步，不是初始化client的问题。非常不好意思，现在更换为CertificatesManager证书管理器，问题已经解决了，非常感谢您的回复！

**Comment by zhanghj94** [comment]
> 谢谢您，问题找到了，是因为我加载平台证书的时候采用的类AutoUpdateCertificatesVerifier不能设置代理，所以一直卡在这一步，不是初始化client的问题。非常不好意思，现在更换为CertificatesManager证书管理器，问题已经解决了，非常感谢您的回复！

你好，我也设置了代理服务器，但是微信返回了400错误，请问是对代理服务器有什么要求吗？

**Comment by zhanghj94** [comment]
> 你好，我也设置了代理服务器，但是微信返回了400错误，请问是对代理服务器有什么要求吗？

你好，我也设置了代理服务器，但是微信返回了400错误，请问是对代理服务器有什么要求吗？

**Comment by xy-peng** [comment]
>  但是微信返回了400错误，请问是对代理服务器有什么要求吗？

请看下具体的错误报文。如果是微信支付返回的，body中应当有具体的错误信息。看看是否能帮助解决问题。

**Comment by zhanghj94** [comment]
> > 但是微信返回了400错误，请问是对代理服务器有什么要求吗？
> 
> 请看下具体的错误报文。如果是微信支付返回的，body中应当有具体的错误信息。看看是否能帮助解决问题。

谢谢，目前是拿nginx做代理服务器，代理非微信支付接口是可以通过的。但是代理微信支付的接口请求不通，因为对nginx使用不是很熟练，找不到具体错误信息
![19d385bcfb0731c13ffee48929203e8](https://user-images.githubusercontent.com/37207075/199638447-234b3a5b-1f3f-42e8-bf61-b8aab8e78d3b.jpg)
