### ISSUE TITLE
如何正确初始化CloseableHttpClient？何时关闭CloseableHttpClient？

### ISSUE THREAD

**Issue by AmosWong1998** [wechatpay-apiv3/wechatpay-apache-httpclient#174]
我的想法是将CloseableHttpClient定义为类成员变量，然后重写afterPropertiesSet()方法，塞入证书等相关信息，但是不知道这样是否合理？是否会导致连接无法释放？
![image](https://user-images.githubusercontent.com/41744494/201811549-e34bc576-7d83-419c-9c9b-40fd890f8619.png)
另外想问下，我每次使用完CloseableHttpClient的时候是否需要显式的close掉？

**Comment by xy-peng** [comment]
你使用的是 Spring 的话， 在 `destory` 中释放呢？

**Comment by AmosWong1998** [comment]
> 

现在这种使用方式对不对 在afterProperties()方法中初始化，我担心这个client一直无法关闭 会导致系统连接过多

**Comment by xy-peng** [comment]
按照 ClosableHttpClient 的定义，用完了之后是需要关闭。
