### ISSUE TITLE
使用DefaultHttpClientBuilder构造出来的HttpClient需要关闭吗？

### ISSUE THREAD

**Issue by sxshunrj** [wechatpay-apiv3/wechatpay-apache-httpclient#175]
com.wechat.pay.java.core.http.HttpClient接口并没有close方法，代码如下：

Config config = new RSAConfig.Builder()
                        .merchantId(merchantId)
                        .privateKeyFromPath(privateKeyPath)
                        .merchantSerialNumber(merchantSerialNumber)
                        .wechatPayCertificatesFromPath(wechatPayCertificatePath)
                        .build();

HttpClient httpClient = new DefaultHttpClientBuilder()
        .readTimeoutMs(3000)
        .writeTimeoutMs(3000)
        .connectTimeoutMs(3000)
        .credential(requireNonNull(config.createCredential()))
        .validator(requireNonNull(config.createValidator()))
        .build();

![image](https://user-images.githubusercontent.com/18591209/202135557-c23e00bc-026a-4b38-a1dd-90da54e0b0a6.png)

**Comment by xy-peng** [comment]
你用的是 `wechatpay-java`，请到对应的repo提issue。
