### ISSUE TITLE
仅签名不验签

### ISSUE THREAD

**Issue by xpp011** [wechatpay-apiv3/wechatpay-apache-httpclient#179]
针对于[下载账单接口](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_8.shtml)要求仅签名不验签，当前sdk不支持吧，我尝试继承修改SignatureExec责任链的executeWithSignature方法，但它是private

**Comment by xy-peng** [comment]
请看 [常见问题](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E8%B4%A6%E5%8D%95)
