### ISSUE TITLE
回调验签失败

### ISSUE THREAD

**Issue by xiaoqi-java** [wechatpay-apiv3/wechatpay-apache-httpclient#181]
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectReader.readValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;
at com.wechat.pay.contrib.apache.httpclient.notification.NotificationHandler.parseBody(NotificationHandler.java:85) ~[wechatpay-apache-httpclient-0.4.8.jar!/:0.4.8]
是不是需要更新对应依赖

**Comment by xy-peng** [comment]
请看 [如何解决Jackson NoSuchMethodError报错](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3jackson-nosuchmethoderror%E6%8A%A5%E9%94%99)

**Comment by xiaoqi-java** [comment]
已解决感谢大佬~
