### ISSUE TITLE
是否提供一个Spring Boot 3.0的支持版本？

### ISSUE THREAD

**Issue by JiahaoLin2018** [wechatpay-apiv3/wechatpay-apache-httpclient#187]
CloseableHttpClient httpClient = WechatPayHttpClientBuilder.create()
                .withMerchant(wxConfig.getMchId(), certSerialNo, privateKeys)
                .withValidator(new WechatPay2Validator(verifier))
                .build();
HttpComponentsClientHttpRequestFactory clientHttpRequestFactory = new HttpComponentsClientHttpRequestFactory(httpClient);
this.restTemplate = new RestTemplate(clientHttpRequestFactory);

当前[wechatpay-apache-httpclient]使用的是org.apache.httpcomponents:httpclient:4.5.13的包
而spring 6.0中HttpComponentsClientHttpRequestFactory目前只支持org.apache.httpcomponents.client5:httpclient5:5.x.x的包

麻烦提供一个基于jdk17支持spring boot 3.0版本的SDK，或者有其他解决方案吗？

**Comment by xy-peng** [comment]
能否介绍下你真正的需求，你使用 wechatpay-apache-httpclient 的场景和方式，以便于我们针对建议或者提供合适的解决方案。

**Comment by JiahaoLin2018** [comment]
![image](https://user-images.githubusercontent.com/40542227/218027840-72a8f500-7043-464c-b66a-63811cf3a52c.png)
![image](https://user-images.githubusercontent.com/40542227/218027770-dd970650-0898-4e7e-92bf-70be07865aa4.png)
![image](https://user-images.githubusercontent.com/40542227/218028023-a08f20b9-6394-4083-9367-abb0b61ade75.png)
![image](https://user-images.githubusercontent.com/40542227/218028098-e773e9b4-426b-457f-8777-9cc706a61caa.png)
目前报错的这行代码是由于升级spring 6.0导致的。
由于[spring-web-6.0.2]中的HttpComponentsClientHttpRequestFactory仅支持使用org.apache.hc.client5包下的HttpClient构造生成；
而[wechatpay-apache-httpclient]包支持的HttpClient则是org.apache.http.client包下的HttpClient，所以导致了上述代码报错。

麻烦看一下有什么解决方案？

**Comment by xy-peng** [comment]
将 wechatpay-apache-httpclient 升级到 httpclient5 可能不是好的方案，我们还有很多使用 httpclient4 的开发者。

最终的方案，我们考虑在 wechatpay-java 中提供适配，支持 spring 的 HttpClient。

短期，只能建议你先暂时升级 spring6 😭

**Comment by JiahaoLin2018** [comment]
好的，谢谢，那目前暂时不能进行spring6版本升级了。
若时间充裕时我再将SDK重构成 wechatpay-java，完成该步骤后再进行spring6版本升级。
