### ISSUE TITLE
使用时Verifier没有办法初始化在springboot中

### ISSUE THREAD

**Issue by autumn11** [wechatpay-apiv3/wechatpay-apache-httpclient#190]
在springboot项目中，初始化Verifier会报错
    @Resource
    private Verifier verifier;
报错信息：
Action:

Consider defining a bean of type 'com.wechat.pay.contrib.apache.httpclient.auth.Verifier' in your configuration.

**Comment by Pigeon-fancier** [comment]
因为不支持无参构造吧
`public class CertificatesVerifier implements Verifier {

    private static final Logger log = LoggerFactory.getLogger(CertificatesVerifier.class);
    protected final HashMap<BigInteger, X509Certificate> certificates = new HashMap<>();

    public CertificatesVerifier(List<X509Certificate> list) {
        for (X509Certificate item : list) {
            certificates.put(item.getSerialNumber(), item);
        }
    }

    public CertificatesVerifier(Map<BigInteger, X509Certificate> certificates) {
        this.certificates.putAll(certificates);
    }`
    这里的两个构造都是要传入值的

**Comment by ChaoFengZhu** [comment]
怎么解决了
