### ISSUE TITLE
jackson版本过低不兼容wechatpay-apache-httpclient0.4.9

### ISSUE THREAD

**Issue by yrenfuture** [wechatpay-apiv3/wechatpay-apache-httpclient#196]
项目使用的jackson 版本是2.10,但使用了wechatpay-apache-httpclient 0.4.9
请问什么版本的wechatpay-apache-httpclient可以兼容 jackson2.10 但又不会影响已经对接的支付

**Comment by xy-peng** [comment]
根据 jackson 的 [releases 文档](https://github.com/FasterXML/jackson/wiki/Jackson-Releases)，2.10 版本已经 end of life 了。

这个库应该不兼容 2.10 版的 Jackson。建议小心谨慎的升级 jackson，或者使用 [wechatpay-java](https://github.com/wechatpay-apiv3/wechatpay-java)，底层使用了 GSON。
