### ISSUE TITLE
NotificationHandlerTest.java示例可能不够清晰

### ISSUE THREAD

**Issue by yrenfuture** [wechatpay-apiv3/wechatpay-apache-httpclient#197]
https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/master/src/test/java/com/wechat/pay/contrib/apache/httpclient/NotificationHandlerTest.java#105
该示例主要是回调通知验签/报文解密的演示
private static final String wechatPaySerial = ""; // 平台证书序列号
该参数可能让开发者不够清晰数据的来源，来源于微信回调通知请求头Wechatpay-Serial

**Comment by xy-peng** [comment]
感谢反馈。“请求头中的证书序列号”，这样表达更精准。

不过，这个库目前已经不主动维护了，除非有安全问题。建议使用 [wechatpay-java](https://github.com/wechatpay-apiv3/wechatpay-java)，欢迎提建议。
