### ISSUE TITLE
证书自动更新里面写死的证书接口地址，内网服务器无法访问

### ISSUE THREAD

**Issue by llllllllu** [wechatpay-apiv3/wechatpay-apache-httpclient#199]
<img width="923" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/assets/40686452/6f6c3971-115d-4b5d-b615-b8aa9416d848">

**Comment by xy-peng** [comment]
建议使用 wechatpay-java，支持使用代理
