### ISSUE TITLE
httpclint 设置 RetryHandler后 重试报空指针

### ISSUE THREAD

**Issue by SnailOfLife** [wechatpay-apiv3/wechatpay-apache-httpclient#20]
抛出异常：
java.lang.NullPointerException: null
	at com.wechat.pay.contrib.apache.httpclient.SignatureExec.execute(SignatureExec.java:48)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)

源码：
if (request.getURI().getHost().endsWith(".mch.weixin.qq.com")) {
      return executeWithSignature(route, request, context, execAware);
    } else {
      return mainExec.execute(route, request, context, execAware);
    }
原因
当执行第一次后，request中 uri的host被置为null,再次重试，抛出此异常

**Comment by ccf0411** [comment]
mark一下

**Comment by xy-peng** [comment]
@SnailOfLife 能贴一下你设置RetryHandler部分的代码吗

**Comment by ccf0411** [comment]
> @SnailOfLife 能贴一下你设置RetryHandler部分的代码吗

你好，我之前也遇到这个问题，业务场景是发生在，微信支付完成后，立马去做查询操作，此时微信如果在处理中，会返回IO异常，IO异常会自动被org.apache.http.impl.execchain的RetryExec捕获并做重试操作，但是由于第一遍请求时，org.apache.http.impl.execchain里的ProtocolExec中，将uri置空了，所以SignatureExec中，request.getURI().getHost().endsWith(".mch.weixin.qq.com")就会报空指针异常。

**Comment by xy-peng** [comment]
@ccf0411 你好，没太明白具体的场景，还需要你提供更详细的说明

> 业务场景是发生在，微信支付完成后，立马去做查询操作，此时微信如果在处理中，会返回IO异常

是异步接口？是哪个接口出现的？前面的“完成”是指请求已经发送并收到了微信支付的应答吗？

**Comment by SnailOfLife** [comment]
> > @SnailOfLife 能贴一下你设置RetryHandler部分的代码吗
> 
> 你好，我之前也遇到这个问题，业务场景是发生在，微信支付完成后，立马去做查询操作，此时微信如果在处理中，会返回IO异常，IO异常会自动被org.apache.http.impl.execchain的RetryExec捕获并做重试操作，但是由于第一遍请求时，org.apache.http.impl.execchain里的ProtocolExec中，将uri置空了，所以SignatureExec中，request.getURI().getHost().endsWith(".mch.weixin.qq.com")就会报空指针异常。


如果你选择拉下这个包自己编译，只需要 在这段代码改为
       String host = request.getURI().getHost();
        if(host==null){
            host = request.getTarget().toHostString();
        }
        if (host.endsWith(".mch.weixin.qq.com")) {
            return executeWithSignature(route, request, context, execAware);
        } else { 
            return mainExec.execute(route, request, context, execAware);
        }
如果你不想clone 下来改了再编译，就可以照葫芦画瓢写个 SignatureExec和WechatPayHttpClientBuilder。
注意 默认的 httpclient 内置的重试规则不会重试post 请求，我选择了自己继承 DefaultHttpRequestRetryHandler 改写其构造器实现， 目前看起来没什么问题。关于这个NoHttpResponseException 异常 有更好的解决方式，请告诉我，谢谢

**Comment by SnailOfLife** [comment]
> @ccf0411 你好，没太明白具体的场景，还需要你提供更详细的说明
> 
> > 业务场景是发生在，微信支付完成后，立马去做查询操作，此时微信如果在处理中，会返回IO异常
> 
> 是异步接口？是哪个接口出现的？前面的“完成”是指请求已经发送并收到了微信支付的应答吗？


我是复用连接的时候，连接已失效导致抛出 NoHttpResponseException。这个时候通过httpclient重试机制时用到的。由于默认的重试机制问题，只有在get的时候遇到这个bug,也就是查询操作。

**Comment by SnailOfLife** [comment]
> @SnailOfLife 能贴一下你设置RetryHandler部分的代码吗

httpClient = builder
                    .setKeepAliveStrategy(myStrategy)
                    .evictExpiredConnections()
                    .setRetryHandler(new MyStandardHttpRequestRetryHandler(3,false))
                    .setDefaultRequestConfig(defRequestConfig).build();

其中MyStandardHttpRequestRetryHandler 是模仿 StandardHttpRequestRetryHandler 添加 this.idempotentMethods.put("POST", Boolean.TRUE);
但是在正常情况下是复现不出来这个问题的。我调试的时候是将请求超时时间设置为1ms,并重写HttpRequestRetryHandler 中retryRequest 方法始终返回true。才复现了此问题。

线上是因为采用连接池管理复用连接。当选取一个使用过的连接时，有可能已断开抛出NoHttpResponseException 而导致重试的。这个问题只在新的微信分中遇到过。

**Comment by xy-peng** [comment]
> String host = request.getURI().getHost();
> if(host==null){
> host = request.getTarget().toHostString();
> }
> if (host.endsWith(".mch.weixin.qq.com")) {
> return executeWithSignature(route, request, context, execAware);
> } else {
> return mainExec.execute(route, request, context, execAware);
> }

这样改是个办法。

我来重现下，尽快修复这里。确实是个隐患，非常感谢 @SnailOfLife @ccf0411 提供信息。

**Comment by xelloss00x** [comment]
@xy-peng 请问下，bug修复了吗
