### ISSUE TITLE
奇怪bug复现

### ISSUE THREAD

**Issue by sharkbb** [wechatpay-apiv3/wechatpay-apache-httpclient#201]
uat和生产共用一套 生产没问题但是uat拿不到证书是为什么呢？
![图片](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/assets/103086112/509b3d04-e0a6-4334-a9fa-f9a276bdbe99)
是我用的版本不对吗？这是我的pom文件
      <dependency>
            <groupId>com.github.wechatpay-apiv3</groupId>
            <artifactId>wechatpay-apache-httpclient</artifactId>
            <version>0.4.2</version>
        </dependency>

**Comment by sharkbb** [comment]
![图片](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/assets/103086112/e3b78641-d126-4d57-8af3-d4eab668df99)
这是具体的代码

**Comment by xy-peng** [comment]
看贴的代码很正常。如果是测试环境，是否存在商户号或私钥不一致的情况？建议加一些日志，把出错时的商户号和私钥（为了避免泄漏打印摘要，不要打印原文）输出下，看看是否有问题？

**Comment by sharkbb** [comment]
昨天打出来就是同样的商户号和私钥呢   git根本没有可以commit的  而且我配了cicd  所以不会出现商户号不正确的情况 昨天出现这个情况后  我重启了order服务 点击了两次还是同样的问题   但是过了大概5-8分钟 再点击uat环境就恢复了 又可以正常二维码  就挺奇怪的
