### ISSUE TITLE
使用该 sdk 后使用国标加密报错 

### ISSUE THREAD

**Issue by YANG18642029437** [wechatpay-apiv3/wechatpay-apache-httpclient#202]
<img width="1033" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/assets/43190741/07cf3b9e-b917-47b0-a045-b82ca766376f">
<img width="1554" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/assets/43190741/bb1f53b2-45ba-4acc-beba-116f499ae8d3">

**Comment by YANG18642029437** [comment]
取消掉该 sdk 就没问题了

**Comment by xy-peng** [comment]
用了这个库之后，非调用微信支付的其他环节使用国密报错了吗？
