### ISSUE TITLE
API_v3定时更新证书功能

### ISSUE THREAD

**Issue by jeff1ry** [wechatpay-apiv3/wechatpay-apache-httpclient#205]
昨天的问题看了吗？有什么解决方法吗 还在等待解决方法呢
![Uploading 12.15.png…]()

**Comment by jeff1ry** [comment]
![12 15](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/assets/153799510/1ba1fd92-43b9-4cc4-beda-9d23652af31f)

**Comment by xy-peng** [comment]
在之前的 issue 上讨论吧
