### ISSUE TITLE
日尼玛，能不能学学对面支付宝

### ISSUE THREAD

**Issue by AZiMiao1122** [wechatpay-apiv3/wechatpay-apache-httpclient#21]
你看你写的什么破玩意

**Comment by xy-peng** [comment]
有什么问题或者建议可以提出来

**Comment by xy-peng** [comment]
从设计目标来看，这个库并不是为了提供开箱即用的SDK，而是通过decorator的方式将签名验签的能力提供给开发者，让开发者能方便的整合到自己已有的生产系统中去。同时，也提供了敏感信息加解密等，降低开发者对于新协议的接入成本。

如果有疑问，意见或者建议，希望大家在开放的社区上以沟通交流的方式提出来

**Comment by xiaozhiliaoo** [comment]
@xy-peng  所以您建议使用v3还是v2，感觉v2比较方便啊，v3接入好麻烦

**Comment by xiaozhiliaoo** [comment]
> 从设计目标来看，这个库并不是为了提供开箱即用的SDK，而是通过decorator的方式将签名验签的能力提供给开发者，让开发者能方便的整合到自己已有的生产系统中去。同时，也提供了敏感信息加解密等，降低开发者对于新协议的接入成本。
> 
> 如果有疑问，意见或者建议，希望大家在开放的社区上以沟通交流的方式提出来

问题是大家只想尽快看到效果，让程序run起来，这个decorator感觉达不到开箱即用的感觉，希望可以提供开箱即用的SDK或者录个视频啊，支付宝视频教学很全，接入花了几小时，这微信接了两天还没搞懂，，，

**Comment by xiaozhiliaoo** [comment]
> 你看你写的什么破玩意

老哥稍安勿躁🤣🤣🤣

**Comment by Cashew-wood** [comment]
我也想说微信支付sdk真垃圾，没见过这么烂的，写的一堆没有用
