### ISSUE TITLE
这个框架支持服务商账户使用吗

### ISSUE THREAD

**Issue by Josh-Zhen** [wechatpay-apiv3/wechatpay-apache-httpclient#24]
如题，望解答

**Comment by Josh-Zhen** [comment]
因为现在要实现的功能是服务商帮商户创建优惠券

**Comment by xy-peng** [comment]
完全可以

**Comment by Josh-Zhen** [comment]
WechatPayHttpClientBuilder builder = WechatPayHttpClientBuilder.create()
        .withMerchant(merchantId, merchantSerialNumber, merchantPrivateKey);

这个“merchantId”,"merchantSerialNumber","merchantPrivateKey",这三个值是传商户的还是服务商的

**Comment by xy-peng** [comment]
传服务商的。这是身份验证信息，谁发请求就填谁的。
