### ISSUE TITLE
下载账单文件报错？不支持下载账单请求？

### ISSUE THREAD

**Issue by yhfzd** [wechatpay-apiv3/wechatpay-apache-httpclient#25]
jar version: 0.1.6
请求地址：v3/billdownload/file?token=xxxxxx&tartype=gzip
异常：h.auth.WechatPay2Validator     : parameter error: empty Request-ID

**Comment by xy-peng** [comment]
1. 我们账单下载实现上少了Request-ID，在验签时报错了。我们安排一下。
2. 账单下载本身是没有带签名的，可参考证书下载时[关闭验签](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E5%B9%B3%E5%8F%B0%E8%AF%81%E4%B9%A6)。另外再自行验证下载的账单文件的哈希值跟之前申请账单时获取的哈希值。注：仅在下载账单时不验签。

**Comment by lankydog** [comment]
@xy-peng 好的 ，谢谢
