### ISSUE TITLE
自动更新证书只保存最新的，回调验签在证书替换后可能会有问题

### ISSUE THREAD

**Issue by wonderlq** [wechatpay-apiv3/wechatpay-apache-httpclient#26]
自动更新证书只保存最新的，支付回调通知里证书序列号可能是旧的，这样回调通知找不到适配的证书。是否应该把最近的旧证书保留？

**Comment by xy-peng** [comment]
没有这个问题吧，你看看当前的[代码](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/master/src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/AutoUpdateCertificatesVerifier.java)。

自动更新拉取到证书后，将所有有效的证书放到`newCertList`中初始化的新verifier的。

而验签和回调都是根据证书序列号，取对应的证书进行验签的。

**Comment by wonderlq** [comment]
明白。如果自动更新拉取到的证书list有最近的旧证书，就不会有问题。👍

**Comment by xy-peng** [comment]
> 明白。如果自动更新拉取到的证书list有最近的旧证书，就不会有问题。👍

放心，这个一定有
