### ISSUE TITLE
下载证书的时候请求头不需要设置Authorization？

### ISSUE THREAD

**Issue by jingshenbusi6530** [wechatpay-apiv3/wechatpay-apache-httpclient#27]
在HttpClientBuilderTest.getCertificateTest()这个测试代码中，只在请求头中设置了Accept，而官方文档https://wechatpay-api.gitbook.io/wechatpay-api-v3/jie-kou-wen-dang/ping-tai-zheng-shu
明确需要设置Authorization，和User-Agent

**Comment by xy-peng** [comment]
这就是这个库存在的意义。拦截器会帮你计算签名，组装Authorization并设置到请求头中的。

**Comment by jingshenbusi6530** [comment]
@xy-peng 您说的这个拦截器在哪里？不会是SignatureExec.executeWithSignature()这个方法吧？？还是需要自己实现？

**Comment by xy-peng** [comment]
准确的说，是通过扩展httpclient的责任链，实现了签名和验签相关的事宜，实现在[这里](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/master/src/main/java/com/wechat/pay/contrib/apache/httpclient/SignatureExec.java#L62)

**Comment by jingshenbusi6530** [comment]
多谢回复。大佬的设计思路，让我这初级水平的人有点费解，为啥要通过扩展httpclient的方式来实现呢？😂😂



---原始邮件---
发件人: "Xiaoyu PENG"<notifications@github.com&gt;
发送时间: 2020年9月8日(周二) 晚上10:45
收件人: "wechatpay-apiv3/wechatpay-apache-httpclient"<wechatpay-apache-httpclient@noreply.github.com&gt;;
抄送: "jingshenbusi6530"<1210919159@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wechatpay-apiv3/wechatpay-apache-httpclient] 下载证书的时候请求头不需要设置Authorization？ (#27)




 
准确的说，是通过扩展httpclient的责任链，实现了签名和验签相关的事宜，实现在这里

**Comment by xy-peng** [comment]
我们注意到，很多Java开发者接入微信支付是使用的apache httpclient，所以我们想尝试一种方式可以无侵入的实现签名和验签。这样我们的开发者还可以使用已有的生产框架或者代码来接入APIv3。

而httpclient提供的责任链模式，似乎是可以达到这一个目标的（欢迎开发者们反馈是不是真正达到了预期。。。）

**Comment by jingshenbusi6530** [comment]
@xy-peng 不少人在使用这个https://github.com/Wechat-Group/WxJava
开源的SDK来做微信相关的开发，对v2版本的接口支持很不错，有关v3接口的还不完善，是否会考虑协助完善下。

**Comment by xy-peng** [comment]
我们有在关注他们，他们[实现的方式](https://github.com/Wechat-Group/WxJava/tree/master/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/v3)跟我们当前的方式很类似。多亏他们能帮我们把业务接口的支持做好 :-)
