### ISSUE TITLE
和RestTemplate配合使用时，POST请求返回401

### ISSUE THREAD

**Issue by OnskySun** [wechatpay-apiv3/wechatpay-apache-httpclient#32]
版本0.2.1签名默认的实现 WechatPay2Credentials ，使用如下代码获取body用于签名：
 body = EntityUtils.toString(((HttpEntityEnclosingRequest) request).getEntity());
但RestTemplate创建的是BufferedHttpEntity，里面没有编码信息。编码信息是存在request的Header里的，所以导致无法获取编码而使用缺省的ISO_8859_1，如果body里有中文，就会导致签名验证失败，返回401. 
暂时的解决方案是实现自己的Credentials，改为从request里获取编码。希望下个版本能解决这个问题。

**Comment by xy-peng** [comment]
你是下面这样子配合RestTemplate使用的吗？
```
RestTemplate restTemplate = new RestTemplate(new HttpComponentsClientHttpRequestFactory(wechatpayHttpClient)));
```

**Comment by xy-peng** [comment]
只支持utf-8，可能EntityUtils.toString(entity, StandardCharsets.UTF_8)这样就可以了
