### ISSUE TITLE
调用敏感信息解密报 解密失败

### ISSUE THREAD

**Issue by MyGitHubTool** [wechatpay-apiv3/wechatpay-apache-httpclient#33]
调用微信人脸认证  获取实名认证信息的接口 时，接口调用成功 但是在解密敏感信息的时候失败了，报错 ，这个是什么原因
![image](https://user-images.githubusercontent.com/15224359/99936077-38bda480-2d9d-11eb-8e16-e20245a19180.png)

**Comment by xy-peng** [comment]
其他接口解密有成功过吗？

建议检查下，是否使用的商户私钥进行解密的。

**Comment by MyGitHubTool** [comment]
> 其他接口解密有成功过吗？
> 
> 建议检查下，是否使用的商户私钥进行解密的。

谢谢，和微信那边调试的时候通过过了，人脸认证敏感信息解密 和v3接口提供的解密方式还是有些不同。改了方法之后解密成功了

**Comment by MyGitHubTool** [comment]
人脸认证的解密方法见下图 避免下一个对接的人踩坑
![image](https://user-images.githubusercontent.com/15224359/100183704-94616c80-2f1a-11eb-87d4-928d3d39d2f7.png)

**Comment by xy-peng** [comment]
嗯，业务侧已经反馈了，底层加密的padding方式跟API的实现方式不一样。接口后面增加一个参数可以选择padding的模式，用来处理这种特殊的情况。
