### ISSUE TITLE
有下载账单封装的请求吗？

### ISSUE THREAD

**Issue by CrossLee** [wechatpay-apiv3/wechatpay-apache-httpclient#34]
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/bill/chapter3_3.shtml

**Comment by xy-peng** [comment]
之前有回答过，可以参考 #25 。我把账单下载加入示例把。

**Comment by xy-peng** [comment]
如何下载账单，已更新至[常见问题](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/master/README.md#%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E8%B4%A6%E5%8D%95)。
