### ISSUE TITLE
withMerchant(String merchantId, String serialNo, PrivateKey privateKey)

### ISSUE THREAD

**Issue by xiumin1993** [wechatpay-apiv3/wechatpay-apache-httpclient#35]
serialNo是什么含义，从哪儿获取啊？

**Comment by xy-peng** [comment]
商户证书序列号。请参考以下的文档。

1. [什么是证书序列号](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/master/README.md#%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E8%B4%A6%E5%8D%95)
2. [什么是证书](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/master/README.md#%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E8%B4%A6%E5%8D%95)
3. [如何获得证书](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/master/README.md#%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E8%B4%A6%E5%8D%95)
4. [什么是商户证书](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/master/README.md#%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E8%B4%A6%E5%8D%95)
