### ISSUE TITLE
SDK中没有现成的验签方法

### ISSUE THREAD

**Issue by 943332358** [wechatpay-apiv3/wechatpay-apache-httpclient#36]
在SDK中看到了验签的逻辑，但是貌似没有看到提供现成的验签方法。如果存在的话，麻烦说明一下

**Comment by xy-peng** [comment]
可以参考下[CertificatesVerifier](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/master/src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/CertificatesVerifier.java)的 verify 方法
