### ISSUE TITLE
微信支付太恶心

### ISSUE THREAD

**Issue by wsjyz** [wechatpay-apiv3/wechatpay-apache-httpclient#38]
mchid、openid 、notify_url、out_trade_no这类命名有的是全小写，有的是下划线分割。7、8年前就是这样，v3版还是这吊样。用java出来起来很反感

**Comment by xy-peng** [comment]
http api使用snake_case是很常见的。不仅微信支付是这样，业界包括友商的很多api，比如[GitHub](https://docs.github.com/en/rest)，[PayPal](https://docs.github.com/en/rest)，都是snake_case的。

另一方面，参数命名跟编程语言是无关的。想象一下，换成CamelCase的话，go/python的小伙伴是不是跟你一样吐槽呢？建议在实现时model中使用CamelCase，只要在序列化或反序列化时转换成snake_case就可以了。

**Comment by xiaozhiliaoo** [comment]
> mchid、openid 、notify_url、out_trade_no这类命名有的是全小写，有的是下划线分割。7、8年前就是这样，v3版还是这吊样。用java出来起来很反感

你反序列化回来写成notifyUrl就行啦
