### ISSUE TITLE
请问，图片上传接口可以使用该httpclient包实现吗？

### ISSUE THREAD

**Issue by masoca** [wechatpay-apiv3/wechatpay-apache-httpclient#4]

**Comment by xy-peng** [comment]
目前还不行，听到一些需求和反馈了。如果有需要的话，我找时间写一下吧。欢迎大家pr。

**Comment by fufengyuan** [comment]
httpclient上传图片有大小限制，只能上传10多kb的图片，超过了就不行了

**Comment by masoca** [comment]
> 目前还不行，听到一些需求和反馈了。如果有需要的话，我找时间写一下吧。欢迎大家pr。

多谢解答~
