### ISSUE TITLE
企业付款的api 还是只支持xml么 有没有对应新的api

### ISSUE THREAD

**Issue by unavoid** [wechatpay-apiv3/wechatpay-apache-httpclient#40]
![image](https://user-images.githubusercontent.com/30950560/106127591-a4573000-6199-11eb-9ed1-8fd8c2d9e707.png)

**Comment by xy-peng** [comment]
暂时不行，业务还未提供，可以去[开发者社区](https://developers.weixin.qq.com/community/pay)反馈
