### ISSUE TITLE
使用spring的RestTemplate配置，签名会失败

### ISSUE THREAD

**Issue by mmzhi** [wechatpay-apiv3/wechatpay-apache-httpclient#42]
具体原因是WechatPay2Credentials类中的buildMessage方法，EntityUtils.toString会将utf-8默认转换成GBK，再拼接签名，就会导致签名不一致

**Comment by xy-peng** [comment]
EntityUtils.toString(entity)会使用entity中设置的字符集的。直接给entity设置成utf-8字符集就好了，而且微信支付只支持utf-8。

**Comment by mmzhi** [comment]
RestTemplate，默认是不会在entity写入字符集信息的，现在目前做法，就是我把该项目原来整个复制下来，EntityUtils.toString强制使用UTF-8字符集转换

**Comment by xy-peng** [comment]
这个问题理论上应该是在RestTemplate侧解决的，你 @mmzhi 看看[stackoverflow](https://stackoverflow.com/questions/29392422/how-can-i-tell-resttemplate-to-post-with-utf-8-encoding)上的建议行不行？

```
RestTemplate restTemplate = new RestTemplate();
restTemplate.getMessageConverters()
        .add(0, new StringHttpMessageConverter(StandardCharsets.UTF_8));
```
