### ISSUE TITLE
平台证书序列号不一致

### ISSUE THREAD

**Issue by hechaoqi123** [wechatpay-apiv3/wechatpay-apache-httpclient#44]
环境如下
` public void init() throws IOException {
        // 加载商户私钥
        PrivateKey merchantPrivateKey = PemUtil.loadPrivateKey(new ByteArrayInputStream(priKey.getBytes("utf-8")));

        // 加载平台证书（mchId：商户号,mchSerialNo：商户证书序列号,apiV3Key：V3秘钥）
        AutoUpdateCertificatesVerifier verifier = new AutoUpdateCertificatesVerifier(
                new WechatPay2Credentials(MCH_ID, new PrivateKeySigner(mchSerialNo, merchantPrivateKey)), MCH_KEY.getBytes("utf-8"));
        MinipayTest.verifier = verifier;

        // 初始化httpClient
        httpClient = WechatPayHttpClientBuilder.create()
                .withMerchant(MCH_ID, mchSerialNo, merchantPrivateKey)
                .withValidator(new WechatPay2Validator(verifier)).build();
    }`
微信支付普通服务商模式下，特约商户进件《提交申请单》接口需要上送平台证书序列号，通过AutoUpdateCertificatesVerifier 获取到的证书（X509Certificate）并没有包含序列号（或者说包含的序列号不是微信接口所需要的的序列号）

https://wechatpay-api.gitbook.io/wechatpay-api-v3/jie-kou-wen-dang/ping-tai-zheng-shu
verifier.getValidCertificate().getSerialNumber()返回的序列号与上述接口返回的序列号不一致。

**Comment by xy-peng** [comment]
AutoUpdateCertificatesVerifier就是从上述接口获取的平台证书。证书可能有多个，getValidCertifificate()返回的都是可用的。

每个商户都有自己对应的平台证书，是不是前后的商户号不一致呢？建议提供一下具体的报文或日志吧，看代码看不出来什么呀

**Comment by xy-peng** [comment]
没有后续反馈，先关闭吧

**Comment by zjxjwxk** [comment]
我发现getSerialNumber().toString(16)转成十六进制可能就一样了。
