### ISSUE TITLE
微信支付V3接口有沙箱环境吗？

### ISSUE THREAD

**Issue by CodePlayer** [wechatpay-apiv3/wechatpay-apache-httpclient#45]
微信支付V3接口有沙箱环境吗？找遍了官方文档，也没看到有所提及。

1、如果有的话，请求地址也是加 /sandboxnew 前缀吗？比如："/sandboxnew/v3/pay/transactions/jsapi"？

2、获取平台证书的接口"https://api.mch.weixin.qq.com/v3/certificates"，也需要加 "'/sandboxnew/" 前缀吗？
比如 "https://api.mch.weixin.qq.com/sandboxnew/v3/certificates"？

3、沙箱环境获取密钥的专属接口"https://api.mch.weixin.qq.com/sandboxnew/pay/getsignkey"，里面需要加 "/v3" 吗？
比如 "https://api.mch.weixin.qq.com/sandboxnew/v3/pay/getsignkey" ？

你们的接口文档感觉做得真差劲，经常是东一榔头、西一棒槌的。看你们 v3 的代码从开发到现在也有两年多了，文档居然还如此不完善。

**Comment by xy-peng** [comment]
1. v3暂时还没有沙箱，我们有计划
2. 文档的问题可以具体一点吗？

**Comment by CodePlayer** [comment]
你们 V3 版本 的文档感觉不适合开发，部分示例代码比较散，貌似没有发现一个完整的接口 Demo，比如部分示例代码只是构建了一个 HttpClient 实例，有些代码只是签名的生成 或 验签 的示例，有些只有获取平台证书的示例代码。

此外，举一个具体的例子：文档里面有写道，向微信支付发起请求时，要在请求头里面加一个 `Authorization` 请求头，并写明了具体的规则。

我们按照文档指定的规则，参照该页面的示例，完成了发送请求时附加 `Authorization` 请求头 的功能 。

结果发现返回的是 Nginx 的 400 Bad Request 页面，也没有任何细节的提示。

最后多方摸索，才发现使用 wechatpay-apache-httpclient 时并不需要自己设置 `Authorization` 请求头，代码里面已经封装了这部分的处理逻辑。

另外，APP第一次发起支付的时候，只输入了一个 `prepay_id`，其他参数都是错的，居然也支付成功了
（当时还以为调通了 -_-）。

结果，第二次开始就失败了。使用 APP 调起 SDK 的时候，一直返回 code = -100。好像在文档里面也没找到这个错误码代表啥。

还有很多类似的细节，哎，说多了都是泪。

**Comment by CodePlayer** [comment]
你好，请问你们在什么情况下会返回【201 商户订单号重复】？
我们使用同一个订单号，在没有完成支付的情况下重复调起SDK发起支付请求，有些订单号重复发起，就没有问题。
有些订单号重复发起 就提示【201 商户订单号重复】。

**Comment by xy-peng** [comment]
1. 具体接口的文档，需要看[接入指引](https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter2_5_2.shtml#part-6)
2. 具体的业务问题，可以去社区发帖问或者使用文档页面右下方的“技术支持”入口呼唤在线技术支持。这里只处理SDK相关的事宜。

**Comment by hfxu** [comment]
@xy-peng 请问现在 v3 接口有沙箱环境了吗？

**Comment by ciawin** [comment]
@xy-peng 请问现在 v3 接口有沙箱环境了吗？

**Comment by dungeonsnd** [comment]
今年 3125 年了，请问 v3 接口有沙箱环境了吗？  :)

**Comment by fengzheng2018** [comment]
已经3126年了，请问 v3 接口有沙箱环境了吗？

**Comment by NeroBlackstone** [comment]
经3126年了，请问 v3 接口有沙箱环境了吗？

**Comment by FKVV** [comment]
> 经3126年了，请问 v3 接口有沙箱环境了吗？

直接怼线上
