### ISSUE TITLE
能不能提供一个quick start，方法全部mock了，unit test一次过，这么看sdk真难受，无从下手

### ISSUE THREAD

**Issue by xiaozhiliaoo** [wechatpay-apiv3/wechatpay-apache-httpclient#46]
不知道你提供那么多调用方式我到底用哪一个，

**Comment by xy-peng** [comment]
我来补充

**Comment by xy-peng** [comment]
@xiaozhiliaoo 请看下[草稿](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/blob/xy-peng-online_edit/README.md)，是否对你有帮助？

**Comment by xy-peng** [comment]
close, #48

**Comment by xiaozhiliaoo** [comment]
> close, #48

谢谢大佬的例子，前些日子要接，最后有些事情耽搁了，现在又开始接了😂
