### ISSUE TITLE
请问有碰到nginx 400的问题吗

### ISSUE THREAD

**Issue by zhangchengtest** [wechatpay-apiv3/wechatpay-apache-httpclient#5]
微信支付请求 请问有碰到nginx 400的问题吗

**Comment by xy-peng** [comment]
微信支付API v3使用HTTP状态码来表示请求处理的结果。

+ 请求处理失败时，如缺少必要的入参、支付时余额不足，将会返回4xx范围内的错误码。

建议阅读一下[接口规则-错误信息](https://wechatpay-api.gitbook.io/wechatpay-api-v3/wei-xin-zhi-fu-api-v3-jie-kou-gui-fan#cuo-wu-xin-xi)，结合应答包体中的code/message确认具体的错误原因。

**Comment by zhangchengtest** [comment]
虽然不知道原因 但是用普通的httpclient反而成功返回了

**Comment by xy-peng** [comment]
能发一下应答头部中的request-id么？我们查一下。

**Comment by zhangchengtest** [comment]
回调解密报文的时候碰到javax.crypto.AEADBadTagException: Tag mismatch!这个问题 用的AesUtil这个类 请问有碰到过吗

**Comment by xy-peng** [comment]
apiV3密钥错误了？tag mismatch是AES/GCM解密时校验位验证不通过

**Comment by zhangchengtest** [comment]
是的 密钥错了 感谢
