### ISSUE TITLE
自动更新平台证书，旧证书失效后，下载新证书验签失败

### ISSUE THREAD

**Issue by zhengmx1993** [wechatpay-apiv3/wechatpay-apache-httpclient#50]
在AutoUpdateCertificatesVerifier实例初始还首次下载微信平台证书，下次更新平台证书是发现距离上次更新时间超过1小时后就下载新证书列表更新；但并没有**定时间隔刷新**。
 假如有如下场景：应用程序已启动，程序也首次自动下载并更新了平台证书，在旧证书失效微信平台会在更新证书，**在新旧证书都有效期间，没有用户使用程序(实际是没有触发下载最新证书)**，但在旧证书完全失效后只有新证书有效，这时有用户使用，触发验签去调下载证书接口,但此时verifier非空(有旧证书)，会使用缓存的旧证书来验签，这时验签失败，不能更新证书，除非重启程序重新实例化AutoUpdateCertificatesVerifier对象。 不知道是不是一个bug。

![image](https://user-images.githubusercontent.com/41073927/114506538-88294200-9c64-11eb-88d2-8d6c5e9e7bce.png)

**Comment by xy-peng** [comment]
是有这个问题，只是触发的机率比较低。证书会提前至少一天就提供下载的。

建议开发者参考[平台证书更新指引](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay5_0.shtml)的建议实践吧。

**Comment by xy-peng** [comment]
也欢迎pr改进。

**Comment by sanshengs** [comment]
请问不突破接口的频率限制( 单个商户号1000 次/s)的情况下,取消60分钟限制,每次请求都更新证书,能否解决?

**Comment by xy-peng** [comment]
> 请问不突破接口的频率限制( 单个商户号1000 次/s)的情况下,取消60分钟限制,每次请求都更新证书,能否解决?

可以，但是不建议这样子用

1. 随着业务发展，后面遇到频率限制了怎么办？
2. 每次都更新证书，再验签会增加请求的延时，可能影响到终端用户的体验。

还是建议参考[平台证书更新指引](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay5_0.shtml)吧

**Comment by xy-peng** [comment]
fix in #88
