### ISSUE TITLE
apiv3版本有官方sdk吗？

### ISSUE THREAD

**Issue by xiaozhiliaoo** [wechatpay-apiv3/wechatpay-apache-httpclient#51]
请教下，apiv3有官方sdk吗，旧版本还有sdk，https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=11_1，
这个wechatpay-apache-httpclient算sdk吗？

**Comment by xy-peng** [comment]
会有的，包含业务接口的sdk，等待等待。

**Comment by xiaozhiliaoo** [comment]
> 会有的，包含业务接口的sdk，等待等待。

谢谢~明白了

**Comment by AbnerMai** [comment]
为什么通知回调验签总是失败？没找着解决方法啊

**Comment by Tervest** [comment]
这sdk真的是 还不如自己封装

**Comment by Eric-Lee-Handyman** [comment]
目前正在规划新版本的Java SDK，新版本会带业务API，请耐心等待。
