### ISSUE TITLE
申请退款API可以不写notify_url，一直轮询拉取查询单笔退款API可以吗？

### ISSUE THREAD

**Issue by xiaozhiliaoo** [wechatpay-apiv3/wechatpay-apache-httpclient#52]
您好😁，请教两个问题：
疑问1：申请退款API是v3/refund/domestic/refunds，我可以不选择微信主动通知，不传notify_url，而是被动拉取查询退款v3/refund/domestic/refunds/{out_refund_no} 可以吗？
疑问2：银行卡支付的退款1-3个工作日到账，那么回调通知也是1-3工作日吗？😊

**Comment by wxpaytechsupport** [comment]
第一个问题：可以。
第二个问题：是的。
后续如果支付接口相关问题可前往[微信支付社区](https://developers.weixin.qq.com/community/pay)咨询，会有专人解答您的问题~

**Comment by xiaozhiliaoo** [comment]
> 第一个问题：可以。
> 第二个问题：是的。
> 后续如果支付接口相关问题可前往[微信支付社区](https://developers.weixin.qq.com/community/pay)咨询，会有专人解答您的问题~

谢谢亲~
