### ISSUE TITLE
APIV2下的单，APIV3能查到吗？

### ISSUE THREAD

**Issue by xiaozhiliaoo** [wechatpay-apiv3/wechatpay-apache-httpclient#53]
什么情况下商户会将APIV2升级到V3？感觉两套API区别很大，签名也不一样，社区文档APIV2的单，APIV3还退不了，

**Comment by xy-peng** [comment]
> 社区文档APIV2的单，APIV3还退不了

可以退。

> 什么情况下商户会将APIV2升级到V3？

v3的目标是：保证支付安全，带给商户简单、一致且易用的开发体验。新业务都会遵循v3的标准进行开发。后续我们也会针对v3提供相关的开发工具。

总而言之，建议新接入的商户使用v3。

**Comment by xiaozhiliaoo** [comment]
> > 社区文档APIV2的单，APIV3还退不了
> 
> 可以退。
> 
> > 什么情况下商户会将APIV2升级到V3？
> 
> v3的目标是：保证支付安全，带给商户简单、一致且易用的开发体验。新业务都会遵循v3的标准进行开发。后续我们也会针对v3提供相关的开发工具。
> 
> 总而言之，建议新接入的商户使用v3。

谢谢~
