### ISSUE TITLE
wechatpayCertificates是从哪里来的?

### ISSUE THREAD

**Issue by fe19880924** [wechatpay-apiv3/wechatpay-apache-httpclient#54]
`如果你使用的是HttpClientBuilder或者HttpClients#custom()来构造HttpClient，你可以直接替换为WechatPayHttpClientBuilder。我们提供相应的方法，可以方便的传入商户私钥和微信支付平台证书等信息。

import com.wechat.pay.contrib.apache.httpclient.WechatPayHttpClientBuilder;

//...
WechatPayHttpClientBuilder builder = WechatPayHttpClientBuilder.create()
        .withMerchant(merchantId, merchantSerialNumber, merchantPrivateKey)
        .withWechatpay(wechatpayCertificates);
// ... 接下来，你仍然可以通过builder设置各种参数，来配置你的HttpClient

// 通过WechatPayHttpClientBuilder构造的HttpClient，会自动的处理签名和验签
HttpClient httpClient = builder.build();

// 后面跟使用Apache HttpClient一样
HttpResponse response = httpClient.execute(...);
参数说明：

merchantId商户号。
merchantSerialNumber商户证书的证书序列号，请参考什么是证书序列号和如何查看证书序列号。
merchantPrivateKey字符串格式的商户私钥，也就是通过证书工具得到的apiclient_key.pem文件中的内容。
wechatpayCertificates微信支付平台证书的实例列表，用于应答签名的验证。你也可以使用后面章节提到的“自动更新证书功能”。`

从公众平台的哪个功能有设置的，没有找到（mp.weixin.qq.com）

**Comment by xy-peng** [comment]
请先看一下[获取平台证书API](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay5_1.shtml)和[平台证书更新指南](平台证书更新指引)，稍后我更新到ReadMe中去。

**Comment by Skylab-git** [comment]
请问更新了吗？我也不明白 wechatpayCertificates实例列表是什么，可以写一个实例的获取例子吗？

**Comment by xy-peng** [comment]
稍微补充说明一下。建议使用`AutoUpdateCertificatesVerifier`，这样更简单。后面会进一步简化初始化的设计。

**Comment by fe19880924** [comment]
@xy-peng  已经对接成功
