### ISSUE TITLE
签名失败

### ISSUE THREAD

**Issue by archer4117** [wechatpay-apiv3/wechatpay-apache-httpclient#6]
这个sdk的签名只代理了 .mch.wexin.qq.com的域名，现在我这边接入的好几个接口都是pay.weixin.qq.com 请问这种要怎么处理

**Comment by xy-peng** [comment]
具体是哪些接口？智慧导购吗？

**Comment by archer4117** [comment]
https://pay.weixin.qq.com/index.php/xphp/cmchcircle/query_guider
https://pay.weixin.qq.com/index.php/xphp/cmchcircle/create_customer_guide
 类似这样的接口

**Comment by hxmdn** [comment]
> https://pay.weixin.qq.com/index.php/xphp/cmchcircle/query_guider
> https://pay.weixin.qq.com/index.php/xphp/cmchcircle/create_customer_guide
> 类似这样的接口

请问你的问题解决了吗，我也遇到了这个问题。

**Comment by xy-peng** [comment]
@archer4117 这些接口后续会切回到api.mch.weixin.qq.com。httpclient不计划支持，建议你新写一个类ClientExecChain。
