### ISSUE TITLE
你不觉得开始里面少了一个PrivateKey么

### ISSUE THREAD

**Issue by radiantHang** [wechatpay-apiv3/wechatpay-apache-httpclient#61]
PrivateKey merchantPrivateKey = PemUtil .loadPrivateKey(new ByteArrayInputStream(privateKey.getBytes("utf-8")));
应该用这个，不说的话完全不知道要用哪个PrivateKey

**Comment by xy-peng** [comment]
[开始](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%BC%80%E5%A7%8B)已经补充了关键参数，你再看看？还是是说其他的文档？

**Comment by radiantHang** [comment]
看到有提到PrivateKey是商户私钥，却没有说明怎么怎么构建PrivateKey

**Comment by xy-peng** [comment]
知道意思了，我补充一个引用，具体操作说明放到常见问题中
