### ISSUE TITLE
javax.crypto.BadPaddingException: 解密失败

### ISSUE THREAD

**Issue by 279832523** [wechatpay-apiv3/wechatpay-apache-httpclient#65]
try {
             ciphertext = RsaCryptoUtil.decryptOAEP(text, merchantPrivateKey);
        } catch (BadPaddingException e) {
            e.printStackTrace();
        }
        return ciphertext;

调用这个方法返回报错

**Comment by xy-peng** [comment]
BadPaddingException，意味着不是密钥用错了，就是密文不对或不完整
