### ISSUE TITLE
使用AutoUpdateCertificatesVerifier可能导致的性能低下与验签不通过问题与建议;

### ISSUE THREAD

**Issue by Jack-bytes** [wechatpay-apiv3/wechatpay-apache-httpclient#66]
1. 如果使用AutoUpdateCertificatesVerifier, 且开发者在使用api时, 每次都使用WechatPayHttpClientBuilder创建httpclient, 在验签步骤将每次都进入AutoUpdateCertificatesVerifier#verify的if判断(因为instant一直为null), 导致同一时间只能执行一次请求;
2. 使用池管理httpclient, 在AutoUpdateCertificatesVerifier的这一行
.withValidator(verifier == null ? (response) -> true : new WechatPay2Validator(verifier))
如果用户超过12个小时没有任何请求, 且在同一时间, 平台证书已经更新且已经启用, 也就是说这时候用户本地是没有最新的那一个证书的, 那么在下载证书这个步骤的验签中会使用旧证书验签, 结果就是一直验签不过, 可以在那一行加一个或条件, 超过10个小时就在验签时也直接返回true

**Comment by iamsxm** [comment]
有一说一，微信的sdk和其他的比太烂了。都跑去用第三方的了

**Comment by xy-peng** [comment]
谢谢你的建议，确实还有很多不足。

对于第一个问题，我们正在尝试在Go SDK中实现一个证书管理器，用一个“证书池”来维护不同商户的平台证书，类似 `HttpClientConnectionManager`。后面应该会“移植”过来。

第二个问题，下载证书时应该根据`verifier.getValidCertificate()`的结果来判断证书有效性。这个可以改，也欢迎PR。

**Comment by leyou240** [comment]
> 有一说一，微信的sdk和其他的比太烂了。都跑去用第三方的了

求第三方的github地址

**Comment by diaohancai** [comment]
> > 有一说一，微信的sdk和其他的比太烂了。都跑去用第三方的了
> 
> 求第三方的github地址

+1
