### ISSUE TITLE
APIV3异步通知结果验签

### ISSUE THREAD

**Issue by NotExistUserName** [wechatpay-apiv3/wechatpay-apache-httpclient#68]
请问目前的API V3版本有提供Java版本的异步通知验签吗,现在按照官方文档的说明进行签名验证,一直通过不了

**Comment by xy-peng** [comment]
暂时没有。

我这边计划一下。

**Comment by NotExistUserName** [comment]
哈哈哈，我这边按照官方的实现了一套。目前已投入生产，表现良好。
注意以下几点(其他的就按照官方提示操作即可,授人以渔哈):

1. 接受微信回调参数时应该使用HttpServletRequest#getInputStream的方式获取参数，切勿使用@RequestBody进行获取，一定要保证验证参数的顺序与微信回调的完全一致
2. 验签方法构造可按照该兄弟的写法(建议编写时可将魔法值抽取出来)：https://developers.weixin.qq.com/community/develop/doc/0006ac6c95c950c47b1b9a4445b800?highLine=%25E5%25BE%25AE%25E4%25BF%25A1%25E6%2594%25AF%25E4%25BB%2598%25E5%259B%259E%25E8%25B0%2583%25E9%25AA%258C%25E7%25AD%25BE
3. Java支持直接通过initVerify(Certificate certificate)初始化对象，初始化方法可参照(注意关闭流,官方貌似没没关闭流)AutoUpdateCertificatesVerifier源码中的CertificateFactory cf = CertificateFactory.getInstance("X509");
        X509Certificate x509Cert = (X509Certificate) cf.generateCertificate(
            new ByteArrayInputStream(cert.getBytes("utf-8"))
        );//cert即从微信获取的有效平台证书,获取时需要校验有效期,如果过期应该重新获取

**Comment by xy-peng** [comment]
欢迎 PR 代码 @NotExistUserName 

另外，没有关闭流具体是指？

**Comment by NotExistUserName** [comment]
new了一个流，并没有使用try-with-resources或finally进行流关闭,我理解的是应该是要关闭的，我点击generateCertificate()方法进去也是没有关闭的，不知是我理解有误还是。目前我实现方法是使用了try-with-resources进行了关闭的。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wechatpay-apiv3/wechatpay-apache-httpclient"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wechatpay-apiv3/wechatpay-apache-httpclient] APIV3异步通知结果验签 (#68)





 
欢迎 PR 代码 @NotExistUserName
 
另外，没有关闭流具体是指？

**Comment by xy-peng** [comment]
> new了一个流，并没有使用try-with-resources或finally进行流关闭,我理解的是应该是要关闭的，我点击generateCertificate()方法进去也是没有关闭的，不知是我理解有误还是。目前我实现方法是使用了try-with-resources进行了关闭的。

按照[ByteArrayInputStream](https://docs.oracle.com/javase/8/docs/api/java/io/ByteArrayInputStream.html)文档中的描述，是不用关闭的。

> Closing a ByteArrayInputStream has no effect.

不过，关闭是个好习惯。这样未来这里的约定发生了变化也能适配。
