### ISSUE TITLE
AesUtil中Base64.getDecoder().decode(ciphertext)异常 java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit

### ISSUE THREAD

**Issue by yayozen** [wechatpay-apiv3/wechatpay-apache-httpclient#69]
java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit
不是所有订单的偶尔1-2个订单
好像是密文长度不对，hashmap接的微信回调参数，请指点

**Comment by xy-peng** [comment]
需要提供更多的信息，贴一下代码或者完整的有问题的报文？

**Comment by yayozen** [comment]
已联系客户拿到正确报文，是自己系统底层框架问题，谢谢
