### ISSUE TITLE
下单-签名-验签等能否提供更完整详细的demo

### ISSUE THREAD

**Issue by langtengyun** [wechatpay-apiv3/wechatpay-apache-httpclient#72]
一句和以前一样就带过了。这样对于没有开发之前支付。希望有提供更详细的demo，对新老开发人员提升开发效率。网上资料找了一大堆

**Comment by xy-peng** [comment]
@langtengyun 为什么关闭了？你能详细说说在哪些方面能更详细一些呢？

对于更详细的demo，目前有在推进中，时间上不会很快。我们的目标是 SDK、文档、demo 三者能协同起来，真正能改善接入过程的开发者体验。
