### ISSUE TITLE
验签报错

### ISSUE THREAD

**Issue by HeLodier** [wechatpay-apiv3/wechatpay-apache-httpclient#73]
![image](https://user-images.githubusercontent.com/36906180/129145797-e7d5280c-5696-4dad-95b2-0c83af2bf10d.png)

**Comment by xy-peng** [comment]
调用的函数`decryptOAEP`是敏感信息解密的函数，并非验签。验签可以看`auth`下的两个`verifier`的实现

**Comment by HeLodier** [comment]
![image](https://user-images.githubusercontent.com/36906180/129157979-f0ab203d-f554-461d-b880-b9745cbfc00b.png)
这种呢，情况也是这样的吗，
另外，我直接用AutoUpdateCertificatesVerifier的verify方法，是可以验签的吗

**Comment by xy-peng** [comment]
verify用是可以的。不过0x5b是`[`，0x20是空格，验签的输入数据你是不是弄错了？

**Comment by HeLodier** [comment]
已经处理了，原因是web项目，后台接收到的加密数据，+ 号全部转为了 空格， 需要重新转回来。然后就可以了
