### ISSUE TITLE
请问httpClient 可以搞成单例的bean吗，会不会有安全风险

### ISSUE THREAD

**Issue by yannaixin** [wechatpay-apiv3/wechatpay-apache-httpclient#75]
@Bean
    public HttpClient getWechatPayHttpClient(){

        AutoUpdateCertificatesVerifier verifier = new AutoUpdateCertificatesVerifier(
                new WechatPay2Credentials(wechatPayConfig.getMerchantId(), getPrivateKeySigner()),
                wechatPayConfig.getApiV3Key().getBytes(StandardCharsets.UTF_8));
        WechatPayHttpClientBuilder builder = WechatPayHttpClientBuilder.create()
                .withMerchant(wechatPayConfig.getMerchantId(), wechatPayConfig.getMerchantSerialNumber(), getMerchantPrivateKey())
                .withValidator(new WechatPay2Validator(verifier));
        HttpClient httpClient = builder.build();
        return httpClient;
    }

**Comment by xy-peng** [comment]
理论上没有并发的风险。如果有问题，欢迎反馈。
