### ISSUE TITLE
签名参数乱码问题

### ISSUE THREAD

**Issue by rheff** [wechatpay-apiv3/wechatpay-apache-httpclient#8]
本地实测时发现WechatPay2Credentials.java中方法buildMessage(String nonce, long timestamp, HttpUriRequest request)在签名处理的时候会产生中文乱码问题
将EntityUtils.toString(xxx) 修改成EntityUtils.toString(xxx，“utf-8”)解决该问题。

**Comment by xy-peng** [comment]
你应该在调用httpclient之前，xxxEntity构造时，指定了对应的字符编码

你可以参考下这个testcase，
https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/commit/88f8d5b35e1e047e33d46ad23a479e6f43c6dc20
