### ISSUE TITLE
改进：使用 AutoUpdateCertificatesVerifier，旧证书失效后下载新证书验签失败问题

### ISSUE THREAD

**Issue by lianup** [wechatpay-apiv3/wechatpay-apache-httpclient#86]
### 背景

- jdk版本：openjdk version "1.8.0_292"
- httpclient 版本：0.2.3

使用 AutoUpdateCertificatesVerifier，在 verify 判断是否自动更新证书的条件是：如果 verifier 为空或者 lastUpdateTime 距离现在大于1小时，才会更新。

可能会出现旧证书在此期间过期，下载新证书，验签失败的问题。

### 改进

- 在 CertificatesVerifier.java 中添加 public boolean existCertificate(String serialNumber) 方法，用于判断本地是否存在序列号对应的证书

  ```java
      public boolean existCertificate(String serialNumber) {
          boolean exist = false;
          for (X509Certificate x509Cert : certificates.values()) {
              if (x509Cert.getSerialNumber().equals(serialNumber)) {
                  exist = true;
              }
          }
          return exist;
      }
  ```

  

- 在 verify 方法中加入判断本地是否存在回包序列号对应证书，若本地不存在对应序列号的证书，也需要更新

  ```java
    public boolean verify(String serialNumber, byte[] message, String signature) {
          if (needUpdateCert(serialNumber)) {
          ...
  ```

  ```java
    protected boolean needUpdateCert(String serialNumber) {
          if (lastUpdateTime == null || verifier == null) {
              return true;
          }
          return !verifier.existCertificate(serialNumber) || Duration.between(lastUpdateTime, Instant.now()).toMinutes() >= minutesInterval;
      }
  ```

- 在 autoUpdateCert 方法增加传入 serialNumber ，用于在构建 validator 的时候判断 verifier 是否设置为空

  ```java
   public void autoUpdateCert(String serialNumber) throws IOException, GeneralSecurityException {
          try (CloseableHttpClient httpClient = WechatPayHttpClientBuilder.create()
                  .withCredentials(credentials)
                  .withValidator(getDownloadCertVerifier(serialNumber) == null ? (response) -> true : new WechatPay2Validator(verifier))
                  .build()) {
            ...
  ```

  ```java
      protected Verifier getDownloadCertVerifier(String serialNumber) {
          // verifier 为空或本地没有对应的平台证书
          if (verifier == null || !verifier.existCertificate(serialNumber)) {
              return null;
          }
          return verifier;
      }
  ```

**Comment by xy-peng** [comment]
在`verify`判断是否要重新获取平台证书时，通过`getValidCertificate()`检查当前是否有可用的平台证书可以吗？

满足以下三个条件之一就重新拉一把

+ 第一次
+ 距离上次获取证书超过了预设时间
+ 当前没有可用的证书

如果没有拉到或者获取锁失败，就验签失败

**Comment by lianup** [comment]
通过 getValidCertificate() 检查，存在问题：如果证书快到期，本地的是旧证书，仍然可用；但是新证书已经在平台上可以下载了，这时候可能有部分请求要用新证书验签。

**Comment by lianup** [comment]
上述方式存在问题：

1. autoUpdateCert 中传入的 serialNumber 为业务请求的回包，而非下载证书请求回包中的 serialNumber ，无法解决可能出现的验签不过问题。
2. 在 verify 中，若有多个线程同时请求，此时只有一个线程能拿到锁更新证书，其他请求继续用旧证书验签，可能导致验签不过。

解决上述问题，可采取自动定时更新方式（类似 GO SDK）。

### 思路

- 提供一个平台证书管理器单例（CertManagerSingleton，枚举类实现），获取 CertManager 实例

- 提供一个平台证书管理器（CertManager），该管理器提供如下方法：

  - 构造方法
    - 若map为空：下载&&更新证书
    - 若线程池为空，初始化&&执行任务
  - 获取对应 serialNumber 的平台证书
  - 获取最新的证书
  - 更新证书
  - 下载证书

  变量：

  - 证书 map <serialNumber, X509Certificate>
  - 单线程线程池（SingleThreadScheduledExecutor）

- AutoUpdateCertificatesVerifier 中，在构造时获取；对平台证书的管理放到 CertManager 中；从 CertManagerSingleton 中获取平台证书。

麻烦看下这样是否有问题，或哪里需要改进。
