### ISSUE TITLE
这sdk  和没有一样 

### ISSUE THREAD

**Issue by sushuangcheng** [wechatpay-apiv3/wechatpay-apache-httpclient#91]

**Comment by xy-peng** [comment]
能说得更具体一点吗？我猜是因为没有包含具体的业务API，不能让开发者最快速搭建应用。

**Comment by sushuangcheng** [comment]
嗯嗯,是的 , 我认为,这个项目既然是承担了微信支付java sdk的身份,那么如果只是帮助构建 httpClient 和 签名 验签 的话 就有些单薄了,其实sdk对于一些经验比较丰富的开发者来说,就是节约一点重复造轮子的时间而已,但是对于一些新手来说,一个功能丰富的sdk 和 比较单薄的sdk 差别还是很大的,可以降低很大的接入成本. 目前这个sdk,没有任何具体业务的api实现,比如APP下单,查单等, 当然有的商户可能不使用这些,但是用不用,是商户的事,有没有却是咱们平台方的事. 当然这只是我个人的想法和建议,可能和平台的战略方向或者想法有冲突.

**Comment by xy-peng** [comment]
你说的没错，对开发者的支持是不够。`wechatpay-apache-httpclient` 是一开始为降低开发者接入成本和技术支持成本的最小解决方案。我们也在计划有业务接口 Java SDK 了。

**Comment by ye21st** [comment]
是的，对于第一次接入微信支付的新手来说。实在太费劲了，线上的在线技术客服，沟通起来也很不方便，很难解决问题。

**Comment by wuchubuzai2018** [comment]
其实可以仿照支付宝API进行设计，设计request对象和model对象，我是有兴趣参与开源sdk的开发的

**Comment by tonitech** [comment]
issue主说出了我的心声，我觉得微信的这个项目写了跟没写一样，跟支付宝的比差太远了

**Comment by longxianlin** [comment]
腾讯用的是C++，阿里用Java，两家程序员的思维逻辑不同，你看腾讯的文档都是很原始的。你要用微信的服务，就接受这种状态吧，建议用回V2。

**Comment by tonitech** [comment]
> 腾讯用的是C++，阿里用Java，两家程序员的思维逻辑不同，你看腾讯的文档都是很原始的。你要用微信的服务，就接受这种状态吧，建议用回V2。

不认同你的观点，程序员开源一个项目难道不应该用产品的思维来设计一个项目吗？产品设计就是要简单，既然是微信的程序员，就应该传承微信的产品设计思想，而不是C++。而且官方的人已经说了今年要做一个我们期望的SDK项目，而不是这种啥都没有封装的。

**Comment by xy-peng** [comment]
希望各位开发者能提出自己的需求，不仅仅接口和请求应答模型，也欢迎提出其他的功能性和非功能性的需求。

**Comment by Eric-Lee-Handyman** [comment]
大家的需求我们已经收到了，需要时间实现。
目前正在规划新版本的Java SDK，新版本会带业务API，请耐心等待。
