### ISSUE TITLE
ScheduledUpdateCertificatesVerifier不能做到对多个商户号配置进行定时更新证书功能

### ISSUE THREAD

**Issue by tinoyoung** [wechatpay-apiv3/wechatpay-apache-httpclient#93]
com.wechat.pay.contrib.apache.httpclient.cert.CertManagerSingleton.init(Credentials, byte[], long)
这里用的单例，导致只有第一次调用这个方法时的商户号配置才会启动定时任务进行更新

我们的业务里可能使用到多个商户号进行收款，这里好像就不支持了.....

**Comment by lianup** [comment]
使用多个ScheduledUpdateCertificatesVerifier是否能满足需求？

**Comment by sanshengs** [comment]
能否提供一个可选本地存储路径? 多个商户号生成的证书存储到不同路径,每次检查路径下证书状态,从而解决多个商户号情况 @lianup
