### ISSUE TITLE
请求一次下载接口是否会返回新旧2份证书

### ISSUE THREAD

**Issue by casecake** [wechatpay-apiv3/wechatpay-apache-httpclient#94]
我在官方文档里看见说会存在新旧证书同时启用的情况，然后看代码中请求证书返回的也是个list，所以这里下载证书应该是新旧证书同时下载的吧。主要我这有需要对多个商户号的证书进行更新缓存，而在singleton中获取证书后会clear一下旧缓存，这个操作我比较害怕，但是又没法测试这种情况，望解答，谢谢

**Comment by casecake** [comment]
同时我自己修改了下代码，实现了多个证书的更新，麻烦帮忙看下会不会有问题
https://github.com/casecake/wechatpay-apache-httpclient/commit/85073b3837d7744d3094a4f99320289a2624918f

**Comment by xy-peng** [comment]
多商户号，涉及到两个方面：
1. 主动发起请求，使用多个 client 可以做到，要自行维护商户号和对应 client 的对应关系。我们再思考下是否要支持多商户号的场景。
2. 定时证书更新，这个我们已经在跟进了，可以在 #93 反馈。

关于返回多个证书场景的测试支持，我们考虑下如何做。 不过，你的代码，我们很难“帮忙看下会不会有问题” 😄

**Comment by casecake** [comment]
嗯嗯，主要是新旧证书同时存在的场景没法手动制造
